### ISSUE TITLE
(?) [Insights] Graphics Under Resource Library have MicroTek Logo

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#10]
**Page Info**
https://test-umb.attune.com/insights/resources/ebooks-and-guides/the-complete-training-program-planning-guide/
https://test-umb.attune.com/insights/resources/ebooks-and-guides/5-step-guide-for-busy-meeting-planners/
https://test-umb.attune.com/insights/resources/ebooks-and-guides/complete-guide-to-cloud-based-virtual-training-labs/

Almost all of the resource library pages have MicroTek logo in graphics

**Describe the bug**
Not sure an issue.  Graphics Under Resource Library have MicroTek Logo.  Almost all of the resource library pages have MicroTek logo in graphics

**Screenshots**

**Additional context**

**Comment by esuger** [comment]
This page also has a MicroTek Logo under the Theater style section.

https://www.attune.com/insights/blog/posts/2019/july/picking-the-right-meeting-room-layout/

**Comment by aj-mclabs** [comment]
Thanks Eric!
For the most part, any posts or press releases with a timestamp in the past will keep MicroTek branding in them. The only exception is CTAs or contact instructions at the very bottom of blogs.

**Comment by esuger** [comment]
Here to:  https://test-umb.attune.com/insights/blog/posts/2016/january/guide-to-choosing-the-best-training-delivery-method/

**Comment by aj-mclabs** [comment]
All resource book renders have been rebranded!

(Sidenote: the graphic in first blog above is OK to stay. Theatre photo was removed from the other blog.)

**Comment by esuger** [comment]
I found one more left over MicroTek graphic:  
https://test-umb.attune.com/insights/resources/tools/virtual-training-room-marketing-kit/

**Comment by aj-mclabs** [comment]
Fixed.
