### ISSUE TITLE
Photos Load Slowly

### ISSUE THREAD

**Issue by Beth-B** [MicroTekAppDev/Attune.Website.Issues#100]
**Page URL**
https://test-umb.attune.com/spaces/

**Describe the bug**
Photos loaded slowly

**To Reproduce**
Opened https://test-umb.attune.com/spaces-to-meet/ - clicked on top links in order- when I got to locations photos loaded slowly- showed blank for a while-  did not happen the second time I clicked through

**Expected behavior**
can it load faster

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]- CHROME- from my laptop

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bdsoko** [comment]
@Beth-B - I can't reproduce this.  Are you still experiencing an issue? If so, what network are you on?

**Comment by Beth-B** [comment]
I was on chrome through my home (xfinity) account.
The photo loaded slowly the first time, but loaded quickly when I went back in.

Thanks!
Beth
630-719-0239

[cid:image001.png@01CDEFE7.7D80F6A0]<http://www.mclabs.com/>
