### ISSUE TITLE
[Careers] Image - Creepy headless people

### ISSUE THREAD

**Issue by Beth-B** [MicroTekAppDev/Attune.Website.Issues#101]
**Page Info**
https://test-umb.attune.com/about/careers/

**Describe the bug**
Photo shows people in chairs- but their heads don't show- is this intentional- looks creepy

**Screenshots**
I have a screen shot- wasn't sure how to save it here- will figure that out- but have one I can send you

**Additional context**

**Comment by Beth-B** [comment]
![Careers](https://user-images.githubusercontent.com/55350599/64985275-1fac9000-d88a-11e9-8a6b-9b34f281a9eb.PNG)

this should be the photo

**Comment by aj-mclabs** [comment]
Displaying as intended.
