### ISSUE TITLE
Insights- Booking request form Text boxes look to big

### ISSUE THREAD

**Issue by Beth-B** [MicroTekAppDev/Attune.Website.Issues#102]
**Page Info**
https://test-umb.attune.com/insights/blog/

**Describe the bug**
Text boxes for entering name/info look really big- first thing I notice when I hit the page
They look that way on the book now page as well- but the large spacing makes it feel homemade somehow

**Screenshots**
I have one I can share- again, not sure how to attach here- will figure that out

**Additional context**

**Comment by Beth-B** [comment]
![insights_textbox](https://user-images.githubusercontent.com/55350599/64985412-64d0c200-d88a-11e9-962f-3915a8560a38.PNG)

Here is the photo

**Comment by aj-mclabs** [comment]
This is the design of all forms on the site. Functioning as intended.
