### ISSUE TITLE
[Pillar] Spaces to Meet: General - What is included in the "all inclusive" meeting?

### ISSUE THREAD

**Issue by Beth-B** [MicroTekAppDev/Attune.Website.Issues#103]
**Is your feature request related to a problem? Please describe.**
I still think we are missing the mark on the Meetings page-  when I open it I am still not sure what your venue is offering me "at a glance".   What is in the all inclusive meeting package?  When I click on the links it speaks to things that are included and things that are not.  So I am unsure what is included and what is not.  We also speak to technology before meeting basics. 
Actually, I like the Training page a bit better for meetings.   

We seem to have the content - I just don't think we are making it easy for people to understand quickly what is included and what is an add on service.
It should be first- What is included in the All inclusive- How are we better or going to make their lives easier- what add on services do we offer.   Here is an example of what I mean- 
https://summitchicago.com/completemeetingpackage

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aj-mclabs** [comment]
Change accepted. A new 'Meeting Package' component has been added.
