### ISSUE TITLE
[Resources] Case Studies - Broken URLs

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#104]
**Page Info**
These two links don't go anywhere.   They were documented in Issue # 13, but the case was closed with only one of the links fixed.

**Describe the bug**

- https://test-umb.attune.com/insights/resources/case-studies/cs3-training-program-expansion-case-study/
- https://test-umb.attune.com/insights/resources/case-studies/cs2-national-training-rollout-case-study/

--

![2019-09-16_13-39-12](https://user-images.githubusercontent.com/55096138/64983993-6947ab80-d887-11e9-9c41-74920706742e.jpg)
**Screenshots**

**Comment by esuger** [comment]
I believe that you verbally told me these URL's have been updated.  Please let me know what the new ones should be. 

Thanks.

**Comment by aj-mclabs** [comment]
@esuger new links:
https://test-umb.attune.com/insights/resources/case-studies/cs3-training-program-expansion-case-study/
https://test-umb.attune.com/insights/resources/case-studies/cs2-national-training-rollout-case-study/

Should be fixed now. Please recheck.

**Comment by esuger** [comment]
Fixed thanks.
