### ISSUE TITLE
Submitting Book Now form returns CAPTCHA error

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#106]
**Page URL**
https://www.attune.com/book-now/

**Describe the bug**
Submitting Book Now form returns CAPTCHA error.   See screen shot.

![2019-09-16_15-32-34](https://user-images.githubusercontent.com/55096138/64991376-6359c680-d897-11e9-9e5f-b2f4f68c2fec.jpg)

**Comment by bdsoko** [comment]
@aj-mclabs - should the reCAPTCHA test be performed on step 1?

**Comment by bdsoko** [comment]
I moved the reCAPTCHA check to the first step to eliminate the need to click back just in case the submission is flagged as spam.

**Comment by esuger** [comment]
Openned a another bug because I can't get past the first step due to error checking.
