### ISSUE TITLE
[Book Now / Contact Form] Telephone links are wrong

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#107]
**Page Info**
https://www.attune.com/book-now/
https://www.attune.com/contact/

**Describe the bug**
The telephone links shouldn't have dashes, and the international phone number link should begin with a + just like the footer.

**Screenshots**
![2019-09-16_15-34-18](https://user-images.githubusercontent.com/55096138/64991929-76b96180-d898-11e9-8c91-94e3c3a0f8f6.jpg)

**Comment by bdsoko** [comment]
@aj-mclabs - I took care of this one.
@esuger  - Please retest.

**Comment by esuger** [comment]
The footer links DO NOT have a leading 1 on the 800 phone number links.   Which standard is correct?  
Probably need to get them synced up to whatever we decide.

**Comment by bdsoko** [comment]
Should be in sync now.
