### ISSUE TITLE
[Venue - DC] Stats - Incorrect total

### ISSUE THREAD

**Issue by JennHardin** [MicroTekAppDev/Attune.Website.Issues#109]
https://test-umb.attune.com/spaces/united-states/district-of-columbia/washington/attune-washington-d-c/

How are you getting total venue capacity numbers? Do we need to work with Bill for capacity information on architectural plans. 548 is a lot more people then the floor can handle.

**Comment by connorsli** [comment]
We can change the numbers to whatever we like. The problem has been the numbers keep changing. I'm not sure who needs to be involved in that process but we need to get a set of numbers that are fire code compliant that everyone can work from. 

The 548 number was from adding up the max capacity in each room as listed on the [current mclabs DC meet page](https://www.mclabs.com/microtek-meet/microtek-meet-washington-dc/). 

I'll leave up to you on who to involve but once there's an agreed-upon set of numbers let us know and we will update accordingly.

**Comment by aj-mclabs** [comment]
Per Kim, changed copy to say 'Total Seats' to avoid mentioning venue capacity totals.
