### ISSUE TITLE
[Resources] Landing Page - Training Program Planning Guide - Missing help text on MQL form

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#11]
**Page Info**
All Resource Pages.
Here is one:  https://test-umb.attune.com/insights/resources/ebooks-and-guides/the-complete-training-program-planning-guide/

**Describe the bug**
In comparison to the other forms,  the email form on every resource library page doesn't have the helper text within the fields.

**Screenshots**

![Bad Form](https://user-images.githubusercontent.com/55096138/64548546-72b79d80-d2f4-11e9-94c8-d005ba7eb6a8.jpg)
![Correct Form](https://user-images.githubusercontent.com/55096138/64548547-72b79d80-d2f4-11e9-9835-031bd7ab1ae8.jpg)

**Additional context**
Also the resource page forms are asking for Dept / Industry.   Are we still tracking this information?  If not, should those fields be removed?

**Comment by aj-mclabs** [comment]
Redundant placeholder text has been removed from SQL and Subscription forms.
