### ISSUE TITLE
[Visitor - DC] Parking - Missing information on daily rate

### ISSUE THREAD

**Issue by JennHardin** [MicroTekAppDev/Attune.Website.Issues#111]
DC Parking is not complimentary.
See current website information as there is a daily rate.
https://test-umb.attune.com/spaces/united-states/district-of-columbia/washington/attune-washington-d-c/visitor-info/

**Comment by connorsli** [comment]
I'm not sure how to handle this, This floorplan matches the one on the [current mclabs meet page.](https://www.mclabs.com/microtek-meet/microtek-meet-washington-dc/)

**Comment by aj-mclabs** [comment]
> I'm not sure how to handle this, This floorplan matches the one on the current mclabs meet page.

@connorsli looks like you replied to the wrong thread

Please add the parking info listed here:
https://www.mclabs.com/room-rentals/microtek-washington-dc/
to here:
https://test-umb.attune.com/spaces/united-states/district-of-columbia/washington/attune-washington-d-c/visitor-info/

**Comment by connorsli** [comment]
@aj-mclabs fixed
