### ISSUE TITLE
[Book Now] Check boxes for internet not making it in Hubspot.

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#114]
**Page URL**
https://www.attune.com/book-now/

**Describe the bug**
The services requested checkboxes are not making it into Hubspot.

![2019-09-16_16-00-01](https://user-images.githubusercontent.com/55096138/64993229-2c85af80-d89b-11e9-9fcb-37669e53e1e1.jpg)

**Comment by esuger** [comment]
This shows empty data in Hubspot.
![2019-09-16_16-01-46](https://user-images.githubusercontent.com/55096138/64993311-58089a00-d89b-11e9-8809-bc3c0c1ecdb5.jpg)

**Comment by esuger** [comment]
I retested this.  Still not working.

**Comment by bdsoko** [comment]
@esuger - I believe I have resolved this issue.  Please re-test.

**Comment by esuger** [comment]
Opened a another issue.  I can't get past step 1 of the book now to test this issue.

**Comment by esuger** [comment]
Check boxes are now making it to Hubspot.
