### ISSUE TITLE
[Venue - NYC] Floor Plan and full facility capacity

### ISSUE THREAD

**Issue by JennHardin** [MicroTekAppDev/Attune.Website.Issues#115]
https://test-umb.attune.com/spaces/united-states/new-york/new-york/attune-new-york-city/

Room 14 was also the office. This needs to be updated as RM 14 was removed and now is a storage room. We don't have a RM 14 or office in NYC anymore. 

Total Venue capacity - We can never accommodate 498 per fire code. This could just be a marketing thing. I would run it by Kim/or Bill

**Comment by connorsli** [comment]
I've let Julie know an she will make this change as she recolors all the floorplans.

**Comment by connorsli** [comment]
The second issue is the same as issue 109. You can see our response in the link below. 

https://github.com/MicroTekAppDev/Attune.Website.Issues/issues/109#issuecomment-533186534

Essentially we just need an agreed-upon set of numbers to work from. They currently match the max capacity of each room totaled together according to the current site.

**Comment by JennHardin** [comment]
AJ you can close out this and 109 - It is fine to list larger numbers. It is more for marketing.
