### ISSUE TITLE
[Keyword - Boston] Best Events - Year present on page

### ISSUE THREAD

**Issue by JennHardin** [MicroTekAppDev/Attune.Website.Issues#117]
https://test-umb.attune.com/spaces/united-states/massachusetts/boston/computer-rooms/
https://test-umb.attune.com/spaces/united-states/massachusetts/boston/classrooms/
https://test-umb.attune.com/spaces/united-states/massachusetts/boston/conference-rooms/
--

I wouldn't advise listing (Fall 2019, Boston & New England) I would just list Fall since this will require you to update the year, every year.

**Comment by connorsli** [comment]
The year has been removed from the Boston Override pages and you should see that reflected across all these pages. 

Can close @aj-mclabs
