### ISSUE TITLE
[Forms] All Forms should have reCAPTCHA enabled

### ISSUE THREAD

**Issue by bdsoko** [MicroTekAppDev/Attune.Website.Issues#119]
Ensure that all forms have reCAPTCHA enabled.

**Comment by connorsli** [comment]
reCAPTCHAv3 has been added to all forms and the error message copied from the SQL form. @bdsoko could you check one or two to make sure it is set correctly? I've deleted the questions and it is not mandatory but want to be sure it's right before moving on.

**Comment by bdsoko** [comment]
Looks like the forms are setup correctly.
