### ISSUE TITLE
[Search] Search Button - Unexpected functionality

### ISSUE THREAD

**Issue by CamLow** [MicroTekAppDev/Attune.Website.Issues#122]
https://test-umb.attune.com/spaces/united-states/georgia/atlanta/classrooms/
--
Page down to the area that reads 
"Looking for another location" 
When I hit the green SEARCH button
I am directed to the top of the page and not to a search engine
This has happened on all of the Keyword override pages  that I have viewed this far.

Page URL: copy and paste here

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bdsoko** [comment]
@aj-mclabs - as this CTA is shared across search and dynamic location pages, jumping to the top won't always work as the search form is not present on dynamic location pages.

**Comment by aj-mclabs** [comment]
Fixed. Please confirm!

**Comment by aj-mclabs** [comment]
Fix confirmed by @bdsoko
