### ISSUE TITLE
Hotels - Text clipping through box (Detroit)

### ISSUE THREAD

**Issue by kopiola** [MicroTekAppDev/Attune.Website.Issues#123]
**Page Info**
Page URL: https://test-umb.attune.com/spaces/united-states/michigan/detroit/detroit-center/visitor-info/
Section: Hotels

**Describe the bug**
Text appears outside the box (using IE 11).

**Screenshots**
![image](https://user-images.githubusercontent.com/55112627/65055918-a4081d00-d935-11e9-8c0c-ee9784d8865b.png)

**Additional context**

**Comment by tomwidel** [comment]
@kopiola - I have updated the IE styling. Can you please re-test (all browsers) and let us know if the issue is fixed?

**Comment by kopiola** [comment]
Checked all three.  All three are looked good.
