### ISSUE TITLE
[Visitor] 'Back to...' Button - Text outside of button

### ISSUE THREAD

**Issue by kopiola** [MicroTekAppDev/Attune.Website.Issues#124]
**Page URL**
Page URL: https://test-umb.attune.com/spaces/united-states/michigan/grand-rapids/grand-rapids-center/visitor-info/

**Describe the bug**
When I view the site at full screen, the text "back to Grand Rapids center" is covered by the button.  However, when I don't view the site at full screen, the text goes outside the button.  See screenshot below.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/55112627/65057354-1a0d8380-d938-11e9-82de-58308e51e558.png)

**Desktop (please complete the following information):**
 - OS: 
 - Browser IE 11

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kopiola** [comment]
I noticed the same thing on the Minneapolis visitor page: https://test-umb.attune.com/spaces/united-states/minnesota/minneapolis/minneapolis-center/visitor-info/

**Comment by bdsoko** [comment]
@aj-mclabs - how do you want to handle this?

**Comment by aj-mclabs** [comment]
@bdsoko We'll standardize this to be 'back to venue' on all pages.

**Comment by aj-mclabs** [comment]
All of these buttons now say 'Back to Venue'
