### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by kimm-att** [MicroTekAppDev/Attune.Website.Issues#126]
https://test-umb.attune.com/spaces/ireland/county-dublin/dublin/dublin-center/visitor-info/

Copied from the website:
Parking
**Jervis** Car Park
Notes: Parking address is 23 **jerviss** Street, North City. The parking facility is just a two-minute walk from Attune Dublin.

Note that under parking, Jervis is spelled two different ways and not capitalized. Not sure which way is correct.

**Comment by connorsli** [comment]
Fixed typo and spacing on the page. Can close @aj-mclabs
