### ISSUE TITLE
Two periods at the end of the sentence

### ISSUE THREAD

**Issue by kopiola** [MicroTekAppDev/Attune.Website.Issues#127]
**Page Info**
Page URL: https://test-umb.attune.com/spaces/united-states/minnesota/minneapolis/minneapolis-center/visitor-info/

Section: Map

**Describe the bug**
There are 2 periods at the end of the sentence.

**Screenshots**
![image](https://user-images.githubusercontent.com/55112627/65059064-f0a22700-d93a-11e9-965c-a9d349cf4d20.png)

**Additional context**

**Comment by connorsli** [comment]
Extra period has been removed. Can close @aj-mclabs
