### ISSUE TITLE
[Venue - Milan] URL 

### ISSUE THREAD

**Issue by kimm-att** [MicroTekAppDev/Attune.Website.Issues#128]
https://test-umb.attune.com/spaces/italy/emilia-romagna/milano-marittima/milan-center/
AND
https://test-umb.attune.com/spaces/italy/emilia-romagna/milano-marittima/milan-center/visitor-info/

URLs are not working. When I copy and paste the URLs above, Milan Center page returns a facility search page and the visitor info page returns an error.

Milan Center URL is actually 
https://test-umb.attune.com/spaces/italy/lombardy/milan/milan-center/

Visitor Info URL is actually
https://test-umb.attune.com/spaces/italy/lombardy/milan/milan-center/visitor-info/

Not sure which URLs are correct.

**Comment by connorsli** [comment]
We had a problem with Umbraco creating Milan in multiple "regions" which was resolved. I believe the second set is correct but I'll let @bdsoko verify that.

**Comment by aj-mclabs** [comment]
Yep, second set of URLs is correct. We changed the region of that location, which changed the URL. URL has been changed on the Project spreadsheet to match.
