### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by kimm-att** [MicroTekAppDev/Attune.Website.Issues#129]
https://test-umb.attune.com/spaces/netherlands/north-holland/amsterdam/amsterdam-center/visitor-info/

Parking
Antarctica Multi-Story Car Park
Notes: Located across from the BCN Amsterdam Arena P10 Plaza Arena Parking: Notes: Parking address is Herikerbergweg 288, 1101 CT Amsterdam, Netherlands

Multiple "Notes" under the parking comments.

**Comment by connorsli** [comment]
There was two listed parking lots that weren't separated. They've been separated and formatted. I also unpublished the empty hotel slice.

**Comment by connorsli** [comment]
Can Close @aj-mclabs
