### ISSUE TITLE
[Visitor - International] Hotel inconsistencies

### ISSUE THREAD

**Issue by kimm-att** [MicroTekAppDev/Attune.Website.Issues#131]
International URLs have multiple inconsistencies. I have noted them on the URLs for Testing Spreadsheet. I consider them low-priority errors that can be addressed after testing. Generally the errors are of this nature:

1) On Visitor Info Pages, headers are inconsistent. "Hotel Listings" versus "Hotels"
2) On Visitor Info Pages, Hotel Listing Content appears, but no hotels are listed
3) On Visitor Info Pages, No hotel or hotel header appears.
4) On Center Pages, No Hotel Slice is included

**Comment by aj-mclabs** [comment]
Fix pending. Some hotel components were disabled pending the addition of new hotels. Waiting on Grant to provide those. (Requested 9/10). Heading language inconsistencies will be addressed when these pages are updated.

**Comment by kimm-att** [comment]
Please review in conjunction with issue 143. Not all hotels are Attune Hotels.

**Comment by aj-mclabs** [comment]
All quick nav and component headings now read 'Hotels' and 'Hotels Nearby' respectively.
