### ISSUE TITLE
[Visitor] Hotels - Phone number formatting

### ISSUE THREAD

**Issue by kopiola** [MicroTekAppDev/Attune.Website.Issues#133]
**Page Info**
Page URL: https://test-umb.attune.com/spaces/united-states/north-carolina/raleigh/raleigh-center/
Section: Hotels & Visitor Info

**Describe the bug**
The facility page for Raleigh has a Hotel section, but when you click to the Visitor Info page, there isn't any hotel information.  Why have a hotel section on the facility page if there isn't any info on the visitor page?

**Screenshots**

**Additional context**

**Comment by kopiola** [comment]
same thing applies to the Raleigh Durham Airport Center at https://test-umb.attune.com/spaces/united-states/north-carolina/raleigh/raleigh-durham-airport-center/

**Comment by connorsli** [comment]
The hotel slices on both venue pages has been unpublished.

**Comment by connorsli** [comment]
We have gotten a hotel list from Mara and both Raleigh venues have non-partner hotels associated.

**Comment by aj-mclabs** [comment]
@connorsli please fix phone number formatting on these hotels

**Comment by connorsli** [comment]
Reformatted,
