### ISSUE TITLE
[GLOBAL] Full-width banners - Text illegible

### ISSUE THREAD

**Issue by mercyme64** [MicroTekAppDev/Attune.Website.Issues#135]
**Page Info**
Page URL: copy and paste here
Section: copy and paste section title here

**Describe the bug**
On all of the banners that contain a background image with HTML text over it, the text is illegible when viewing on iPhone (mobile)

**Screenshots**

**Additional context**

**Comment by aj-mclabs** [comment]
Duplicate of #8
