### ISSUE TITLE
Spacing issue on Cookie Policy Page

### ISSUE THREAD

**Issue by mercyme64** [MicroTekAppDev/Attune.Website.Issues#136]
**Page Info**
https://test-umb.attune.com/cookie-policy/
Section: copy and paste section title here

**Describe the bug**
There is extra space after the first paragraph (on iPhone and Desktop)
Cookie Notice  looks to be a "sub heading" but it does not appear bolded

**Screenshots**

**Additional context**

**Comment by connorsli** [comment]
I've removed the extra space and bolded the "cookie notice". It has the same tags as subsequent subheads on the page.
