### ISSUE TITLE
Bullets not aligned on iPhone 7

### ISSUE THREAD

**Issue by mercyme64** [MicroTekAppDev/Attune.Website.Issues#137]
**Page URL**
Page URL: copy and paste here

**Describe the bug**
Paragraph bullets are not aligned on iPhone 7. The bullets appear to be hanging to the left and are cut off the screen to the left.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bdsoko** [comment]
Can you re-test as I've believe I found the issue.  You can close this issue if/when it's resolved.

**Comment by mercyme64** [comment]
Issue fixed.
