### ISSUE TITLE
Phone Number on Hamburger Menu (iPhone)

### ISSUE THREAD

**Issue by mercyme64** [MicroTekAppDev/Attune.Website.Issues#138]
**Page URL**
Page URL: copy and paste here

**Describe the bug**
When clicking hamburger menu the phone number in the Utility navigation a message comes up that reads: "This website has been blocked from automatically starting a call. <Ignore> <Allow Call> When you click "Allow Call" then you get another screen that asks if you want to make the call.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bdsoko** [comment]
I only see a similar message on my iPhone when clicking on all the phone numbers quickly.  The message I'm getting is "This website is repeatedly trying to open another application.".  I can not reproduce the issue your reporting.  When I click a single number, I get prompted to call.

**Comment by mercyme64** [comment]
I get the message "This website has been blocked from automatically starting a call" on every number I touch on iPhone 7. When I click "Allow Call", then I am taken to the live telephone number to call.

**Comment by bdsoko** [comment]
Going to close issue.  Feel free to re-open if others can replicate this issue.
