### ISSUE TITLE
Valid Emails addresses are failing error check

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#139]
**Page URL**
https://www.attune.com/book-now/

**Describe the bug**
Valid Emails addresses are failing error check

![2019-09-17_12-41-30](https://user-images.githubusercontent.com/55096138/65065825-cd7e7400-d948-11e9-9dac-8a2710f40868.jpg)

**Comment by bdsoko** [comment]
We had an invalid regex.  All fixed now.
