### ISSUE TITLE
[Visitor - Doha] Hotels - No hotels listed

### ISSUE THREAD

**Issue by angels-mclabs** [MicroTekAppDev/Attune.Website.Issues#142]
**Page Info**
Page URL: 
https://test-umb.attune.com/spaces/qatar/doha/doha/doha-center/

There is a hotel area but it is blank - if there are no hotels should it be removed?

**Comment by connorsli** [comment]
Removed the empty hotel slice from both Doha pages.

**Comment by aj-mclabs** [comment]
Hotels added.
