### ISSUE TITLE
[Visitor] Hotels - Copy (discounted vs. not)

### ISSUE THREAD

**Issue by kimm-att** [MicroTekAppDev/Attune.Website.Issues#143]
Facility Pages - Many are affected.

We need to decide how to handle hotels on pages where we have no real hotel partners. Right now, the content is shared so the hotel slices on the Visitor Info pages all say the same thing. We say:
Discounted Hotels Nearby
Attune has worked hard to negotiate great rates at hotels near our facilities so that you can receive the best prices. To learn more about our hotel partners or to make a reservation, click on the links below. Be sure to request the Attune rate when booking your room. 

When we have no "Attune Rate", how do we adjust this language where it is not appropriate? Today, our content reads that we have some "recommended" hotels. We do not tell the user to ask for our rate unless we have one. We need to address this for those situations where we have no hotel partners, but rather we "suggest" hotels. We'll look silly is someone is asking for our rate and the hotel doesn't know who we are. Is there a way to have other content appear for the pages where we have no partner hotels? It could also be shared with many locations, just slightly different.

**Comment by aj-mclabs** [comment]
Conditional logic has been added that will change the copy when a particular venue lists partner hotels. Existing default hotel language has been removed.
