### ISSUE TITLE
[Pillar] Spaces to Meet: Tech Support - Swap bullet order

### ISSUE THREAD

**Issue by Beth-B** [MicroTekAppDev/Attune.Website.Issues#144]
https://test-umb.attune.com/spaces-to-meet/

 I  think I might remove that and change the order to move down the remote attendee access bullet.  Presentation tools and the internet not working are two of a planners biggest challenges/frustrations.  That and having no tech around to help when they need them.   I would call those out first.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aj-mclabs** [comment]
Change made.
