### ISSUE TITLE
[Pillar] Spaces to Meet: Layouts - Use Team vs Pods

### ISSUE THREAD

**Issue by Beth-B** [MicroTekAppDev/Attune.Website.Issues#145]
https://test-umb.attune.com/spaces-to-meet/

On the photos for Pods- can we call them Pods instead and say something like: Team seating- the new alternative to rounds for maximum collaboration (or something like that)

*We should also change our floor plans and capacity charts to say team as most ppl don't know what pods mean, but team seating seems to be a new thing.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aj-mclabs** [comment]
Change made site-wide
