### ISSUE TITLE
[Pillar] Spaces to Meet: Tracker - Move Tracker to last spot under event management

### ISSUE THREAD

**Issue by Beth-B** [MicroTekAppDev/Attune.Website.Issues#147]
https://test-umb.attune.com/spaces-to-meet/

The end to end coordination slice seems to go with the travel and registration slices- having tracker in the middle confuses it.  We should put Tracker as the first slide or the last one.  The last one flows the best to me- but either placement could work.  Just not splitting up the "services" like it seems to now.

**Additional context**

**Comment by aj-mclabs** [comment]
Per Beth's request, End-to-End Event Management order is now as follows:
Event Coordination
Travel
Registration
Tracker
