### ISSUE TITLE
[Resources] Case Study: Full Venue - MicroTek branding

### ISSUE THREAD

**Issue by Beth-B** [MicroTekAppDev/Attune.Website.Issues#148]
Opening full venue case study from this link https://test-umb.attune.com/spaces-to-meet/
(and selecting open as new tab) the tab shows microtek_case-study_full-venue on the tab- 
The URL shows attune- but the tab show microtek

![casestudy](https://user-images.githubusercontent.com/55350599/65132927-648a1100-d9c7-11e9-8061-b2411558dee1.PNG)

**Comment by aj-mclabs** [comment]
fixed.
