### ISSUE TITLE
San Diego Center - Parking area blank

### ISSUE THREAD

**Issue by JennHardin** [MicroTekAppDev/Attune.Website.Issues#149]
Parking title listed but there is not any information.

https://test-umb.attune.com/spaces/united-states/california/san-diego/san-diego-center/visitor-info/
--

**Comment by connorsli** [comment]
The parking is at the Bristol Hotel. If you take another look it includes pricing at $12 a day. The heading/styling is consistent with other pages.

**Comment by aj-mclabs** [comment]
Added the word parking for clarification.
