### ISSUE TITLE
[Rebrand] Video - Dons message is MicroTek chicago tour video

### ISSUE THREAD

**Issue by Beth-B** [MicroTekAppDev/Attune.Website.Issues#151]
https://test-umb.attune.com/about/our-rebrand/

Is Don's message just not uploaded yet?  I see a microtek chicago tour when I click on the video

**Comment by connorsli** [comment]
Yes, this is a placeholder video right now so we could construct the page around the frame. Once Don's video is shot it will be swapped out.

**Comment by aj-mclabs** [comment]
Video pulled until we get the footage from the videographer.
