### ISSUE TITLE
Birmingham- Ghost people

### ISSUE THREAD

**Issue by Beth-B** [MicroTekAppDev/Attune.Website.Issues#152]
https://test-umb.attune.com/spaces/united-states/alabama/birmingham/birmingham-center/

Is the photo of the blurry ghost people intentional?

![blurry ghosts](https://user-images.githubusercontent.com/55350599/65135989-77ebab00-d9cc-11e9-9c95-9bac00ce62db.PNG)

**Comment by connorsli** [comment]
Yes, the ghost people are intentional. It is a shared picture for facilities without quality images serving the same purpose as the picture below on our current site. 
![MicroTek Banner](https://user-images.githubusercontent.com/55112731/65159346-8d2afe80-d9f9-11e9-91f9-ea52500dc64f.PNG)
