### ISSUE TITLE
[Misc] Footer - Text illegible when pages are printed

### ISSUE THREAD

**Issue by CamLow** [MicroTekAppDev/Attune.Website.Issues#153]
https://test-umb.attune.com/cookie-policy/
--

https://test-umb.attune.com/privacy-policy/
--

https://test-umb.attune.com/terms-of-use/
--

When the documents are printed, the information under FOLLOW US,  is not legible.  This is the last page of each document and contains the web site address. 

[misc pages.pdf](https://github.com/MicroTekAppDev/Attune.Website.Issues/files/3626567/misc.pages.pdf)

**Comment by tomwidel** [comment]
@CamLow - we have updated our print styling to address the issue. Can you re-test and let us know the result?

**Comment by bdsoko** [comment]
Issue has been retested by me and can be closed.

**Comment by CamLow** [comment]
Print issues appears corrected.



Camille Lowe
MicroTek - www.mclabs.com<blocked::http://www.mclabs.com/>
V: 630.719.0212
E: camillel@mclabs.com<mailto:camillel@mclabs.com>
