### ISSUE TITLE
[Venue] Venues with less than 3 amenities

### ISSUE THREAD

**Issue by connorsli** [MicroTekAppDev/Attune.Website.Issues#154]
**Page Info**
We

Page URL:
 https://test-umb.attune.com/spaces/qatar/doha/doha/doha-center/

Section: Comfort and Support Come Standard

**Describe the bug**
These icons rotate and show 3 at a time. When a location has less than that the slice looks off-center. In these cases, we'll unpublish this slice. If you see the behavior shown below please comment in this thread with the venue URL.

**Screenshots**
![Less than 3 Amenties](https://user-images.githubusercontent.com/55112731/65164021-ac2d8e80-da01-11e9-9e56-b02423561db6.PNG)

**Comment by aj-mclabs** [comment]
https://test-umb.attune.com/spaces/united-states/alabama/birmingham/birmingham-center/

**Comment by aj-mclabs** [comment]
Amenities section has been removed from venues with less than 3 standard amenities.
