### ISSUE TITLE
[Book Now] SEO - H1 Tag needed

### ISSUE THREAD

**Issue by mercyme64** [MicroTekAppDev/Attune.Website.Issues#155]
**Page Info**
https://test-umb.attune.com/book-now/

We need an H1 on this page. Suggest "Book Now"

**Comment by connorsli** [comment]
No way to get a Book Now to span both the form and contact info that I can see. I can place it above the contact info but it has space above it so it looks off. I've reached out to @bdsoko to see if he has any ideas on how to format it. 

Right now it's unchanged but you can see what the slice would look like in the picture below. 
![Book Now](https://user-images.githubusercontent.com/55112731/65263232-c898fc00-dad1-11e9-8999-c2dc32f7148f.PNG)

**Comment by connorsli** [comment]
It's hard to see but the Book Now side starts lower than the form and continues below the bottom border of it.

**Comment by mercyme64** [comment]
Can put the H1 tag above the form, flush left

**Comment by connorsli** [comment]
Unfortunately not without pushing the form down substantially. It would require us to add another slice which inserts padding of its own in between them.  We can edit the text on the right-hand side but anything on the left is locked into the form component.

**Comment by aj-mclabs** [comment]
Added H1
