### ISSUE TITLE
[Homepage] SEO - H Tags

### ISSUE THREAD

**Issue by mercyme64** [MicroTekAppDev/Attune.Website.Issues#156]
**Page Info**
https://test-umb.attune.com/

There should only be one H1 on this page. Currently there are three. Please make "Spaces to Train" and "Spaces to Meet" H2 tags (in the banner)

**Comment by connorsli** [comment]
Just changing the h1 to h2 messed up the sizing, the CSS class didn't help. I will open up a ticket for Brian to make some CSS tweaks to help out.

**Comment by connorsli** [comment]
Ticket opened. You can keep track of the thread here https://github.com/MicroTekAppDev/Attune.Website.Issues/issues/165#issue-495987573

**Comment by bdsoko** [comment]
Duplicate of #165.  Closing this issue.
