### ISSUE TITLE
font rendering issue

### ISSUE THREAD

**Issue by mercyme64** [MicroTekAppDev/Attune.Website.Issues#158]
**Page URL**
On the Munich, Bavaria search results page..

**Describe the bug**
Would you please check the font on this one and adjust? Right now, it looks "wobbly" as if the letters are different sizes.
![{9254A7B4-BFFC-4308-BA9B-5D9DED41B3AB}](https://user-images.githubusercontent.com/55456145/65184713-16f7bd80-da34-11e9-9bc7-5f7aac825efc.png)

**Comment by bdsoko** [comment]
Issue resolved.
