### ISSUE TITLE
Typo-Computer Room Dynamic Page

### ISSUE THREAD

**Issue by kopiola** [MicroTekAppDev/Attune.Website.Issues#160]
**Page Info**
Page URL: https://test-umb.attune.com/spaces/united-states/arizona/phoenix/computer-rooms/#top
Section: see screenshot. mistake is highlighted.

**Describe the bug**
see screenshot. mistake is highlighted.

**Screenshots**
![image](https://user-images.githubusercontent.com/55112627/65189183-de58e380-da35-11e9-8afc-fc74febf2785.png)

**Additional context**

**Comment by aj-mclabs** [comment]
Fixed.
