### ISSUE TITLE
[Visitor - Dallas] Embedded map - Has Chicago information

### ISSUE THREAD

**Issue by CamLow** [MicroTekAppDev/Attune.Website.Issues#161]
https://test-umb.attune.com/spaces/united-states/texas/dallas/attune-dallas/visitor-info/*Page Info**
 
On the map, the address referenced is  230 W. Monroe...
The address should be 5430 Lyndon B Johnson Freeway.......

![Dallas center with Chicago information](https://user-images.githubusercontent.com/55101037/65255487-9b455180-dac3-11e9-8dbe-b638b25be264.png)

**Comment by connorsli** [comment]
The embed map now shows the correct address.

**Comment by connorsli** [comment]
Can close @aj-mclabs

**Comment by CamLow** [comment]
Confirmed


Camiille Lowe
MicroTek - www.mclabs.com<blocked::http://www.mclabs.com/>
V: 630.719.0212
E: camillel@mclabs.com<mailto:camillel@mclabs.com>
