### ISSUE TITLE
[Keyword Override] Pillar - Use of word Devil

### ISSUE THREAD

**Issue by CamLow** [MicroTekAppDev/Attune.Website.Issues#162]
https://test-umb.attune.com/spaces/united-states/georgia/atlanta/classrooms/

Spaces to Meet section near the bottom of the page.

I believe the word Devil should not be listed on the web page even as a cliche.

![Devil in the details](https://user-images.githubusercontent.com/55101037/65256867-de082900-dac5-11e9-8c48-8e585f1a8a27.png)

**Comment by aj-mclabs** [comment]
This component has been removed from all keyword pages.
