### ISSUE TITLE
[Keyword - Chicago] Remove Garfield Park Conservatory

### ISSUE THREAD

**Issue by CamLow** [MicroTekAppDev/Attune.Website.Issues#163]
https://test-umb.attune.com/spaces/united-states/illinois/chicago/computer-rooms/

Remove the Chicago Garfield Park Conservatory as an attraction to view in Chicago.  Garfield Park area is described as a very High Crime area on the west side of Chicago with no safe route to the Conservatory.  Refer clients to Navy Pier.

**Comment by aj-mclabs** [comment]
Replaced with Shedd Aquarium
