### ISSUE TITLE
Opening "Venue and Services Handbook" replaces current page.

### ISSUE THREAD

**Issue by angels-mclabs** [MicroTekAppDev/Attune.Website.Issues#164]
**Page Info**
Page URL: https://www.attune.com/spaces-to-train/
Section: 
Clicking on https://www.attune.com/media/jiddchnr/venue-services-handbook-updated.pdf
Opens "Venue and Services Handbook" does not open in a new window, it replaces the spaces to train page

**Comment by connorsli** [comment]
@angels-mclabs I can't reproduce this. I just tried and it opened in a new tab which is reflected in the backend settings.

**Comment by aj-mclabs** [comment]
Fixed. In the future, please indicate section or heading where the issue is.
