### ISSUE TITLE
[GLOBAL] Request: Ability to strip H1 tag while maintaining formatting

### ISSUE THREAD

**Issue by connorsli** [MicroTekAppDev/Attune.Website.Issues#165]
**Page URL**
Page URL: https://www.attune.com/ 

**Describe the bug**
There are 3 H1 tags, one for each banner. For SEO reasons we can only have one. We need to be able to tag two of the banners as H2's while maintaining the look of the H1's.

**Comment by bdsoko** [comment]
I updated CSS to support H1 and H2 tags for banner 'spaces text'.  I've changed "spaces to meet" and "spaces to train" content to be H2 tags and confirmed styling is good.
