### ISSUE TITLE
[Venue] Virtual Attendance - Inconsistent content and button/link

### ISSUE THREAD

**Issue by kimm-att** [MicroTekAppDev/Attune.Website.Issues#167]
https://test-umb.attune.com/spaces/canada/quebec/montreal/montreal-center/

The virtual slice does not include exactly the same content as the others and it has a button instead of the "learn more" text. This is the missing text:

Virtual training or meeting events can be initiated from any Virtual Origination Site (see the guide below for the complete list) and participants may attend remote events from any location.

>> Download our Virtual Solutions Guide for more details.

Also, the button becomes unnecessary when this is added.

**Comment by kimm-att** [comment]
Also, the first sentence is different. looks like old content.

**Comment by kimm-att** [comment]
also on the quebec center, same problem


https://test-umb.attune.com/spaces/canada/quebec/quebec-city/quebec-city-center/
--

**Comment by aj-mclabs** [comment]
Looks like these are pulling in an older version of this component.
Investigating.

**Comment by kimm-att** [comment]
and Amsterdam

https://test-umb.attune.com/spaces/netherlands/north-holland/amsterdam/amsterdam-center/

**Comment by kimm-att** [comment]
Singapore
https://test-umb.attune.com/spaces/singapore/singapore/singapore-center/

**Comment by connorsli** [comment]
Both Amsterdam and Singapore have had the old content replaced with the repeatable content used elsewhere.

**Comment by aj-mclabs** [comment]
Fixed.

**Comment by kimm-att** [comment]
Note above that Montreal and Quebec City have same problem. Have you fixed those too?

**Comment by connorsli** [comment]
Those have also been addressed.
