### ISSUE TITLE
[Blog] Page 2 button returns error after completing form

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#168]
**Page URL**
https://www.attune.com/insights/blog/

**Describe the bug**
Click any of the page buttons returns an error.   This error only occurs after the form is filled out on the right.
![2019-09-20_15-55-52](https://user-images.githubusercontent.com/55096138/65358416-29eac900-dbbf-11e9-95c0-555a1d2bedff.jpg)
![2019-09-20_15-53-13](https://user-images.githubusercontent.com/55096138/65358299-db3d2f00-dbbe-11e9-885c-bcd90fbd2dbb.jpg)
![2019-09-20_15-53-20](https://user-images.githubusercontent.com/55096138/65358304-dd06f280-dbbe-11e9-9c26-54f246b7b340.jpg)

**Comment by esuger** [comment]
Note this error only occurs after someone fills out the form on the right.

**Comment by bdsoko** [comment]
issue should be resolved - please reset.

**Comment by esuger** [comment]
Yep working now. Thanks.
