### ISSUE TITLE
[Form] Integreation - Data does NOT make it into hubspot

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#169]
**Page URL**
https://www.attune.com/insights/blog/?page=1

**Describe the bug**
Form data from Blogs does NOT make it into hubspot

![2019-09-20_15-57-11](https://user-images.githubusercontent.com/55096138/65358531-71715500-dbbf-11e9-870e-e5e9c28f8d61.jpg)

**Comment by connorsli** [comment]
Troubleshot this with Brian and verified the submissions are now getting through to HubSpot.

Okay to close @aj-mclabs
