### ISSUE TITLE
[Form] reCaptchav3 error - All blog pages will not allow form submission

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#170]
**Page URL**
https://www.attune.com/insights/blog/posts/2019/july/how-to-maintain-focus-during-virtual-training/

**Describe the bug**
All the blog pages themselves will not allow form submission - Captcha error

![2019-09-20_15-59-45](https://user-images.githubusercontent.com/55096138/65358693-d62caf80-dbbf-11e9-8941-90f88027fcfa.jpg)

**Comment by esuger** [comment]
Note on the same page the form on the bottom is showing the error even though I submitted the form on the right.

![2019-09-20_16-04-17](https://user-images.githubusercontent.com/55096138/65358875-679c2180-dbc0-11e9-85a8-113ad5c3b070.jpg)

**Comment by bdsoko** [comment]
Issue has been resolved.  Please re-test.  Cause - reCATPCHA form field was not unique to page (more than 1 more) so script only applied input_response to only 1 instance.

**Comment by esuger** [comment]
Fixed.  However this did not fix the "next page" bug on the list of blogs page.
