### ISSUE TITLE
[Policy] Cookie Policy - Links missing

### ISSUE THREAD

**Issue by kopiola** [MicroTekAppDev/Attune.Website.Issues#171]
**Page URL**
Page URL: https://test-umb.attune.com/cookie-policy/

**Describe the bug**
In the section in the screenshot below, there are two areas that state "(see how here)".  I would expect a link to a document/website/etc, but there isn't one.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/55112627/65360577-142cd200-dbc6-11e9-808a-03879ba0d773.png)

**Desktop (please complete the following information):**
 - Browser IE 11

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bdsoko** [comment]
Removed verbiage.
