### ISSUE TITLE
[Policy] Cookie Policy - Invalid Link in Cookie Policy (Safari)

### ISSUE THREAD

**Issue by kopiola** [MicroTekAppDev/Attune.Website.Issues#172]
**Page URL**
Page URL: https://test-umb.attune.com/cookie-policy/

**Describe the bug**
When I click the link for "Safari" in the "Control via your browser settings" section, I get a page not found (404) error.

**To Reproduce**
1. Go to 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/55112627/65360688-7f76a400-dbc6-11e9-9ba9-42158c320bbb.png)

**Desktop (please complete the following information):**
 - Browser IE 11

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bdsoko** [comment]
I've update the URL for safari.
