### ISSUE TITLE
[Policy] Terms of Use - Missing Period

### ISSUE THREAD

**Issue by kopiola** [MicroTekAppDev/Attune.Website.Issues#173]
**Page Info**
Page URL: https://test-umb.attune.com/terms-of-use/
Section: Second Paragraph. See highlight in screenshot

**Describe the bug**
Missing period at end of sentence.

**Screenshots**
![image](https://user-images.githubusercontent.com/55112627/65360879-370bb600-dbc7-11e9-822c-bbe1fc798454.png)

**Additional context**

**Comment by aj-mclabs** [comment]
Fixed.
