### ISSUE TITLE
[GLOBAL] Suggested videos shown at end of YouTube videos

### ISSUE THREAD

**Issue by tomwidel** [MicroTekAppDev/Attune.Website.Issues#175]
**Page Info**
Any page hosting YouTube videos
Page URL: https://umb.attune.com/about/our-rebrand
Section: video

**Describe the bug**
Non-Attune related videos are shown at the end of the video.

**Additional context**
All YouTube video URLs should have the following format:
https://youtu.be/VIDEO_ID?rel=0&modestbranding=1

_Parameter notes:_
**rel=0** will only show our related videos at the end of the video
**modestbranding=1** will hide/minimize the YouTube logo

**Comment by connorsli** [comment]
Rebranding Page is done but need to look at Resource Videos

**Comment by connorsli** [comment]
These have all been updated. Although we will need to replace the videos with new branding and we will need this code again.
