### ISSUE TITLE
[Visitor - San Diego] Hotels - Only 1 hotel listed

### ISSUE THREAD

**Issue by angels-mclabs** [MicroTekAppDev/Attune.Website.Issues#176]
**Page Info**
Page URL: https://attune.com/spaces/united-states/california/san-diego/san-diego-center/visitor-info/
Section: On the current site there are 3 hotels listed, on the Attune site there is 1. Is this intentional?

**Comment by connorsli** [comment]
All hotels have been created and are ordered the same as the current site.  The pictures could definitely use some adjustment and I couldn't find a good quality one for The Hotel Palomar, @aj-mclabs we may need to adjust the focus for the two we have.

**Comment by aj-mclabs** [comment]
Image added.
