### ISSUE TITLE
[Resources] Case Study: Healthcare (DaVita) - Content not displaying

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#177]
**Page Info**
https://umb.attune.com/insights/resources/case-studies/cs2-national-training-rollout-case-study/

**Describe the bug**
No summary information on this case study.   Other case studies have a bunch of information on this page.

Not sure if this is intentional.

![2019-09-23_9-47-38](https://user-images.githubusercontent.com/55096138/65436120-3f423c00-dde7-11e9-8635-885f2e6f7792.jpg)

**Screenshots**

**Additional context**

**Comment by aj-mclabs** [comment]
Republished components. Please recheck.

**Comment by esuger** [comment]
Fixed thanks.
