### ISSUE TITLE
[Resources] Case Study: Full Venue - The two lower images don't seem to be sized correctly compared to the rest of the site.

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#178]
**Page Info**
https://test-umb.attune.com/insights/resources/case-studies/full-venue-event-software-company/

**Describe the bug**
The two lower images don't seem to be sized correctly compared to the rest of the site.   The two images take a large portion of the screen, especially on tablets/phones.   I would think they would have the same size compared to the first image.

**Screenshots**
![2019-09-23_9-49-59](https://user-images.githubusercontent.com/55096138/65436372-acee6800-dde7-11e9-93ba-74292d539e33.jpg)
![2019-09-23_9-50-40](https://user-images.githubusercontent.com/55096138/65436375-ae1f9500-dde7-11e9-8fc8-6406c6d19d18.jpg)

**Comment by aj-mclabs** [comment]
Added padding to images in the solution and results sections. Please provide feedback.

**Comment by esuger** [comment]
Much better thanks.
