### ISSUE TITLE
[Global] Virtual Attendance - Animation

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#179]
**Page Info**
https://www.attune.com/spaces/united-states/new-york/new-york/attune-new-york-city/

**Describe the bug**
Is there is a reason why the only image on the website that slides in is the "Virtual Attendance" section.   It is on all pages. 

Is this by design?  Otherwise I would remove this animation as it is distracting.

**Screenshots**
![2019-09-23_10-01-18](https://user-images.githubusercontent.com/55096138/65437283-23d83080-dde9-11e9-8de8-cf3dc1e8dd6d.jpg)

**Additional context**

**Comment by aj-mclabs** [comment]
This is by design. It just attracts more attention because it's the only image component that is not a gallery, so it slides in. The rest are rotating carousels.
