### ISSUE TITLE
[Global] Allow 'meet' and 'train' CSS properties to override default link color

### ISSUE THREAD

**Issue by aj-mclabs** [MicroTekAppDev/Attune.Website.Issues#180]
Per @mercyme64 's direction

**Page URL**
https://test-umb.attune.com/spaces-to-train/
https://test-umb.attune.com/spaces-to-meet/

**Comment by bdsoko** [comment]
Added css to support request. Please verify.

**Comment by aj-mclabs** [comment]
Perfect. Thanks!
