### ISSUE TITLE
[Venue - Denver] Experience Denver - Extra slice

### ISSUE THREAD

**Issue by kimm-att** [MicroTekAppDev/Attune.Website.Issues#184]
https://test-umb.attune.com/spaces/united-states/colorado/denver/attune-denver/

There is extra content on the Denver main page below the Hotel Slice and above the FAQ. For some reason, it says:

Experience Denver
Denver has 300 days of sun, allowing your attendees to experience the city in all its Rocky Mountain glory. When you come to Attune Denver, you’ll soon understand why more than 17.3 million visitors come to the city each year and why it's a top spot for professional events in the U.S.

None of the other facilities seem to have this extra blurb.

**Comment by aj-mclabs** [comment]
@kimm-att Unpublished. This was SEO text that was relocated. Please recheck.
