### ISSUE TITLE
[Keyword Dynamic] City links go nowhere

### ISSUE THREAD

**Issue by Beth-B** [MicroTekAppDev/Attune.Website.Issues#185]
https://test-umb.attune.com/spaces/united-states/arizona/phoenix/classrooms/ 

Under additional cities it shows the city name again -Phoenix in green - and says 8 additional venues in this city.  But, when I click on what seems to be a link, nothing happens- it just brings me right back to the original page.

**Comment by bdsoko** [comment]
I discussed this with @aj-mclabs and have made some changes.  Removed links from city names and AJ will update text.

**Comment by aj-mclabs** [comment]
Discussed this with @Beth-B. Changed approved.
