### ISSUE TITLE
[Keyword - Dynamic] Map view pins

### ISSUE THREAD

**Issue by Beth-B** [MicroTekAppDev/Attune.Website.Issues#187]
https://test-umb.attune.com/spaces/united-states/arizona/phoenix/computer-rooms/

When I go to the Map it shows two options Venues and Additional Cities.
If I click pan on venue it takes me to an orange #1-  If I click on additional cities pan it takes me to a red #1  - not sure what these are supposed to be showing?

**Comment by bdsoko** [comment]
I discussed this with @aj-mclabs and we made some changes.  Please review and comment.

**Comment by aj-mclabs** [comment]
Discussed changes with @Beth-B

**Comment by Beth-B** [comment]
Reviewed with AJ- looks good now.

Thanks!
Beth
630-719-0239

[cid:image001.png@01CDEFE7.7D80F6A0]<http://www.mclabs.com/>
