### ISSUE TITLE
[Testimonial] Howard M - Spelling error in quote

### ISSUE THREAD

**Issue by kopiola** [MicroTekAppDev/Attune.Website.Issues#188]
**Page Info**
Page URL: https://test-umb.attune.com/
Section: Recent Feedback Section

**Describe the bug**
In one of the quotes, "your" is used instead of "you're".

**Screenshots**
![image](https://user-images.githubusercontent.com/55112627/65621522-89632300-df89-11e9-90f7-6072caeca87f.png)

**Additional context**

**Comment by aj-mclabs** [comment]
Fixed!
