### ISSUE TITLE
[Pillar] Spaces to Train: Layout - Image spacing

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#19]
**Page URL**
https://www.attune.com/spaces-to-train/

**Describe the bug**
The "Relaxing Cafe and Lounges Areas" image is butted up right next to the image above it.   The rest of the page shows spacing between the various images / sections.

**Screenshots**
![2019-09-09_13-36-34](https://user-images.githubusercontent.com/55096138/64557514-52450e80-d307-11e9-99d8-309ba8978a8d.jpg)

**Desktop (please complete the following information):**
Windows 10 - Chrome and Firefox

**Additional context**

**Comment by aj-mclabs** [comment]
Added padding to on-site support component
