### ISSUE TITLE
[Blog] Forms - Double Subscription Forms on all blog posts when on mobile

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#190]
**Page URL**
All Blogs have this issue.  Here is one page as an example. https://www.attune.com/insights/blog/posts/2019/august/3-keys-to-building-an-effective-event-registration/

**Describe the bug**

**To Reproduce**
![2019-09-25_15-01-34](https://user-images.githubusercontent.com/55096138/65635287-a9a0db00-dfa5-11e9-83d2-6af74e50c018.jpg)

**Comment by bdsoko** [comment]
Issue has been resolved.  per @aj-mclabs , sidebar pods will be hidden on mobile.

**Comment by aj-mclabs** [comment]
confirmed fixed.
