### ISSUE TITLE
[Visitor - Los Angeles] Hotel - L.A. Cambria missing booking link

### ISSUE THREAD

**Issue by Beth-B** [MicroTekAppDev/Attune.Website.Issues#191]
https://test-umb.attune.com/spaces/united-states/california/los-angeles/los-angeles-center/visitor-info/

Booking link button is missing for this hotel.
There is one on the current mclabs website.

**Comment by connorsli** [comment]
The link has been added and is working. Although the code is MICRO as are lots of our current referral codes, something to think about going forward.

**Comment by Beth-B** [comment]
We can’t change the codes until we can announce the rebrand- it is going to get a bit tricky with the rebrand and the hotel RFP season overlapping like it does.

Thanks!
Beth
630-719-0239

[cid:image001.png@01CDEFE7.7D80F6A0]<http://www.mclabs.com/>
