### ISSUE TITLE
[Search] Results - Recent Events 

### ISSUE THREAD

**Issue by Beth-B** [MicroTekAppDev/Attune.Website.Issues#193]
https://test-umb.attune.com/spaces/united-states/illinois/chicago/training-rooms/

All cities:
Can we add some recent events that have Meeting or Event in the Title- most say Training or Classroom

**Comment by aj-mclabs** [comment]
Sent @bdsoko new use cases for Meeting Room and Conference Room keyword pages.

**Comment by aj-mclabs** [comment]
Change is live on site. Meeting keyword pages now have meeting use cases. We will continue to add more use cases over time.
https://test-umb.attune.com/spaces/united-states/illinois/chicago/meeting-rooms/
https://test-umb.attune.com/spaces/united-states/illinois/chicago/training-rooms/
