### ISSUE TITLE
[Forms - MQL] Thank You Text - Doesn't tell user what happens next.

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#194]
**Page URL**
https://www.attune.com/insights/resources/ebooks-and-guides/the-complete-guide-to-hybrid-learning/

**Describe the bug**
The button says "Get your guide" you fill out the form and it says thank you.    But nothing else happens.    No text says you will get an email with the guide, nothing.   This will be confusing for the user.

Also I don't see a workflow execute in hubspot to actually send the email on the contact.  Please verify this Connor.

**Screenshots**
![2019-09-26_10-13-57](https://user-images.githubusercontent.com/55096138/65701529-0accbb00-e047-11e9-841d-e04f5fa6d008.jpg)
![2019-09-26_10-16-33](https://user-images.githubusercontent.com/55096138/65701534-0bfde800-e047-11e9-8070-1cbf5218eaf8.jpg)

**Comment by aj-mclabs** [comment]
In-line thank yous have been removed. Dedicated thank you pages have been turned on and tested.
