### ISSUE TITLE
[Resources] Selected tab doesn't stay when user hits back button

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#195]
**Page URL**
https://www.attune.com/insights/resources/

**Describe the bug**
[Resource Library]  Selected tab doesn't stay when user clicks into a case study, resource, video, etc and then hits back button.

**Expected behavior**
Selected tab remains..

**Screenshots**
![2019-09-26_10-22-38](https://user-images.githubusercontent.com/55096138/65701892-b83fce80-e047-11e9-8bf3-c2204cc7c4be.jpg)

**Comment by aj-mclabs** [comment]
Site is functioning as intended. Unfortunate side effect of utilizing the tabbed view.
