### ISSUE TITLE
[Blog] 7 Ways to Drive the Success of Your Virtual Training Program - Text Formatting

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#20]
**Page Info**
https://test-umb.attune.com/insights/blog/posts/2015/june/7-ways-to-drive-the-success-of-your-virtual-training-program/

**Describe the bug**
Titles have a mix of bold and un-bold.   List items have the wrong size compared to the title.

**Screenshots**
![2019-09-09_13-45-30](https://user-images.githubusercontent.com/55096138/64557953-59b8e780-d308-11e9-9114-0fbd3a74873f.jpg)

**Additional context**

**Comment by aj-mclabs** [comment]
Formatting fixed. Please re-check.
