### ISSUE TITLE
[Visitor] Directions - Partner facility name location and formatting

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#22]
**Page Info**
https://test-umb.attune.com/spaces/united-kingdom/scotland/aberdeen/aberdeen-center/visitor-info/
https://test-umb.attune.com/spaces/united-kingdom/england/wokingham/wokingham-center/visitor-info/

**Describe the bug**
Facility Name is in the Google Pin.   Not sure we want thay.

**Screenshots**
![2019-09-09_14-31-25](https://user-images.githubusercontent.com/55096138/64560684-9091fc00-d30e-11e9-85e7-bc76b1b2b98c.jpg)

**Additional context**

**Comment by esuger** [comment]
One more:  https://test-umb.attune.com/spaces/qatar/doha/doha/doha-center/visitor-info/

**Comment by esuger** [comment]
One more: https://test-umb.attune.com/spaces/new-zealand/wellington/wellington/wellington-center/visitor-info/

**Comment by esuger** [comment]
https://test-umb.attune.com/spaces/austria/vienna/vienna/vienna-center/visitor-info/

**Comment by aj-mclabs** [comment]
Fix in progress. This component is unique on each visitor page, so these will have to be updated one at a time. Will advise when this component is ready for review again.

**Comment by angels-mclabs** [comment]
@aj-mclabs I'm not sure it's a good idea to hide the facility name on the visitor page. Attendees will not see the name Attune anywhere, they need to know the name of the organization and it is listed next to the map information. A simple google of the address will provide the name.

**Comment by esuger** [comment]
> @aj-mclabs I'm not sure it's a good idea to hide the facility name on the visitor page. Attendees will not see the name Attune anywhere, they need to know the name of the organization and it is listed next to the map information. A simple google of the address will provide the name.

Actually the name of the facility is in the text of the page.  I was only suggesting not having it on the map, since the majority of the other facility pages don't have it on the map.

![2019-09-11_9-24-00](https://user-images.githubusercontent.com/55096138/64705804-25633980-d476-11e9-8520-4e36d7e2e5e7.jpg)

**Comment by angels-mclabs** [comment]
Yes, however, this is the visitor page and if they are looking at the MAP or click into the map from a mobile device I don't see how it's helpful to hide the name on the pin.

**Comment by bdsoko** [comment]
@angels-mclabs - Spoke to @aj-mclabs , how about this as a compromise?

![2019-09-11_12-13-18](https://user-images.githubusercontent.com/11299552/64719455-e640e280-d48d-11e9-84c8-565d7b6cda10.png)

**Comment by angels-mclabs** [comment]
It is my opinion that there is not a reason to remove the name from the pin, but it's just an opinion if you are leaving it this way with the name displayed that's up to you.

**Comment by aj-mclabs** [comment]
Moving forward with @bdsoko 's proposed fix.

**Comment by angels-mclabs** [comment]
There are quite a few visitor pages that are showing this in various forms. Once you are ready for retest we'll need to know what the final information should look like (I assume from the information above it should be Brian's fix).

**Comment by aj-mclabs** [comment]
Fixed:
- https://test-umb.attune.com/spaces/united-kingdom/england/wokingham/wokingham-center/visitor-info/
- https://test-umb.attune.com/spaces/austria/vienna/vienna/vienna-center/visitor-info/

These need to be left the way they are as putting in the address alone puts the user at the wrong end of the street:

- https://test-umb.attune.com/spaces/united-kingdom/scotland/aberdeen/aberdeen-center/visitor-info/
- https://test-umb.attune.com/spaces/united-kingdom/england/wokingham/wokingham-center/visitor-info/

Google forces you to choose a business for these addresses:
- https://test-umb.attune.com/spaces/qatar/doha/doha/doha-center/visitor-info/
