### ISSUE TITLE
[Global] Broken Link List

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#23]
**Page Info**
https://test-umb.attune.com/spaces/singapore/singapore/singapore-center/
https://test-umb.attune.com/spaces/singapore/singapore/singapore-center/visitor-info/

**Describe the bug**
These facility links fail.   They do not go to the facility page just the search page:

**Screenshots**

**Additional context**

**Comment by esuger** [comment]
These links fail too:

https://test-umb.attune.com/spaces/italy/emilia-romagna/milano-marittima/milan-center/
https://test-umb.attune.com/spaces/italy/emilia-romagna/milano-marittima/milan-center/visitor-info/

**Comment by aj-mclabs** [comment]
@esuger Milan URL had to be changed after the export. Try these instead:
https://test-umb.attune.com/spaces/italy/lombardy/milan/milan-center/
https://test-umb.attune.com/spaces/italy/lombardy/milan/milan-center/visitor-info/

I'll update them in the spreadsheet.

**Comment by aj-mclabs** [comment]
@esuger Singapore venue link works just fine for me.
@bdsoko Any ideas on the visitor page?
![singapore-visitor](https://user-images.githubusercontent.com/54995447/64562882-94744d00-d313-11e9-9f8e-b31a93292fdf.PNG)

**Comment by esuger** [comment]
Milan works now.   Only broken link is the singapore Visitors link.

**Comment by aj-mclabs** [comment]
Corrected bug for cities that have no region. Singapore visitor page should be working now. Please advise
