### ISSUE TITLE
[Search]

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#24]
**Page Info**
https://test-umb.attune.com/spaces/?h=f3fd5426b09f656d11165723b833aac0&c=Downers+Grove&rc=IL&rn=Illinois&cc=US&cn=United+States&lat=41.8089191&lng=-88.0111746

**Describe the bug**
Results of the facility search.  The font of the facility name is strange.  Not lined up correctly.

**Screenshots**
![2019-09-09_14-44-52](https://user-images.githubusercontent.com/55096138/64561532-9688dc80-d310-11e9-86d8-f21b09bc4bb1.jpg)

**Additional context**

**Comment by esuger** [comment]
Actually the hotels & directions font on the same page is strange too.

**Comment by aj-mclabs** [comment]
Duplicate issue of #12
