### ISSUE TITLE
[Testimonials] Scroll too quickly

### ISSUE THREAD

**Issue by angels-mclabs** [MicroTekAppDev/Attune.Website.Issues#25]
**Page Info**
Page URL: https://test-umb.attune.com/spaces/

**Describe the bug**
The testimonials and comments from visitors scroll too quickly, was not able to read one before the others moved.

**Comment by aj-mclabs** [comment]
Increased testimonial rotation delay to 6sec site-wide. Please advise.

**Comment by angels-mclabs** [comment]
Looks good.
