### ISSUE TITLE
[Search] Results require scrolling on smaller screens

### ISSUE THREAD

**Issue by angels-mclabs** [MicroTekAppDev/Attune.Website.Issues#27]
**Page URL**
https://test-umb.attune.com/spaces/

**Describe the bug**
On this page when I complete a search that is successful I only see the search results in a small part of the screen and have to scroll to see the results. At first, I wasn't sure that it was even there. I am using a personal laptop with a 15" screen.

**Comment by aj-mclabs** [comment]
Please re-test.
Added an animation to search results component to indicate to user that content has changed.

**Comment by bdsoko** [comment]
@angels-mclabs - we've made some UI tweaks that we think address this issue by simplifying the form (removing padding, borders, background mask, change of background image). In doing so, the search results have been moved up in the view-port.

**Comment by angels-mclabs** [comment]
Yes, search is working much better, thanks!
