### ISSUE TITLE
[Venue] Virtual Attendance - Copy is Chicago Talk

### ISSUE THREAD

**Issue by kimm-att** [MicroTekAppDev/Attune.Website.Issues#28]
https://test-umb.attune.com/spaces/united-states/alabama/birmingham/birmingham-center/

SHARED CONTENT, i believe, so on many facility pages

This sentence (under Virtual Attendance) has too many words in it:
... participants to contribute to the class just like they're right there in the room with you. 

**Additional context**
Should maybe read:
... participants to contribute to the class just like they're in the room with you.

**Comment by aj-mclabs** [comment]
Should be fixed for all venue pages.
