### ISSUE TITLE
[Venue] Hotels - Copy says click link

### ISSUE THREAD

**Issue by kimm-att** [MicroTekAppDev/Attune.Website.Issues#29]
https://test-umb.attune.com/spaces/united-states/alabama/birmingham/birmingham-center/visitor-info/
and all visitor info pages

The page says to click on the link, but there is no link, only a phone number

Perhaps instead say to click on the link or call the number below

**Comment by aj-mclabs** [comment]
Fix in progress. The hotel component is unique on each visitor page, so these will have to be updated one at a time. Will advise when this component is ready for review again.

**Comment by aj-mclabs** [comment]
Conditional logic has been added that will change the copy when a particular venue lists partner hotels. Existing default hotel language has been removed per issue #143
