### ISSUE TITLE
[Visitor] Hotel Listing Consistency

### ISSUE THREAD

**Issue by kimm-att** [MicroTekAppDev/Attune.Website.Issues#30]
https://test-umb.attune.com/spaces/united-states/alabama/birmingham/birmingham-center/visitor-info/

For the hotel information on the Phoenix page, the instructions say:
Call (800) 866-8108 and request the Attune rate.

The Birmingham hotel says:
Call 205-313-2060

Should we not make these consistent? Maybe we don't have a rate in Birmingham?

**Comment by aj-mclabs** [comment]
@kimm-att Correct, Birmingham does not have a partner hotel, so there is no preferred rate or referral link.
