### ISSUE TITLE
[Venue] Amenities: Complimentary Continental Breakfast - Incorrect information

### ISSUE THREAD

**Issue by angels-mclabs** [MicroTekAppDev/Attune.Website.Issues#32]
**Page Info**
Page URL: https://test-umb.attune.com/spaces/australia/victoria/melbourne/melbourne-center/
Section: Complimentary continental breakfast is indicated, although this is an option it is not complimentary at this location specifically and at others. Even at Attune it may not be complimentary depending on your package.

**Comment by aj-mclabs** [comment]
Removed the word complimentary on Melbourne page and Attune venue pages. In the process of removing from other network locations as well.

**Comment by aj-mclabs** [comment]
'Complimentary' has been removed from the 'Continental Breakfast' amenity site-wide.
