### ISSUE TITLE
[Venue] Virtual Attendance - PDF loading over current page content.

### ISSUE THREAD

**Issue by angels-mclabs** [MicroTekAppDev/Attune.Website.Issues#33]
**Page Info**
Page URL: https://test-umb.attune.com/spaces/united-states/tennessee/nashville/nashville-center/
Section: Nashville is not a "VTR" location, however, virtual attendance is indicated. This may be confusing if a prospect requests that service outside of the 30 or so locations that offer it they may be disappointed in the misleading information.

**Comment by angels-mclabs** [comment]
I checked this out, the PDF is still pending and it's loading over my current web content, not sure if that's the intent?

**Comment by aj-mclabs** [comment]
The download PDF link should open in a new tab now. Please verify.

**Comment by angels-mclabs** [comment]
This opens in a new tab now.
