### ISSUE TITLE
[Venue] Hotels - Button link destination

### ISSUE THREAD

**Issue by kimm-att** [MicroTekAppDev/Attune.Website.Issues#34]
https://test-umb.attune.com/spaces/united-states/florida/tampa/tampa-center/

The link for Visitor Info in the black slice opens the same page in a new tab. The link under hotel partners works properly.

**Comment by aj-mclabs** [comment]
This is functioning as intended. In our current implementation, they should both open the Visitor Info page. We could make a change to have the hotel button open to the hotel _section_ of the visitor page, but it's not necessarily the cleanest solution. Let me run my idea by @bdsoko and see what his thoughts are.

**Comment by bdsoko** [comment]
@aj-mclabs , the issue is that the visitor info component is not linking to the visitor info page.  I have updated the link.
