### ISSUE TITLE
[Venue] Dallas: Catering - Grammar

### ISSUE THREAD

**Issue by CamLow** [MicroTekAppDev/Attune.Website.Issues#35]
**Page Info**

Section: copy and paste section title here
https://test-umb.attune.com/spaces/united-states/texas/dallas/attune-dallas/

**Describe the bug**
In the section Delicious Catering Options the sentence reads "Before we accepting a new caterer, we sample the cuisine to ensure it meets our standards".  Should have used the word accept instead of accepting. 

**Screenshots**
 

**Additional context**

**Comment by aj-mclabs** [comment]
Entire catering component  swapped to match 'Spaces to Meet' page.
