### ISSUE TITLE
[Venues] FAQ - Grammatical Error

### ISSUE THREAD

**Issue by kopiola** [MicroTekAppDev/Attune.Website.Issues#36]
**Page Info**
Page URL: https://test-umb.attune.com/spaces/united-states/kentucky/louisville/louisville-center/
Section: FAQ

**Describe the bug**
The word "someone" is shown twice in the question, "Is there someone someone at the facility to assist and direct attendees?"

**Screenshots**

**Additional context**

**Comment by kopiola** [comment]
The same issue is on the Baltimore-North-Center FAQ as well.  It's probably on every venue profile.

**Comment by aj-mclabs** [comment]
Should be fixed on all venue profiles. Please re-check!

**Comment by kopiola** [comment]
yep
