### ISSUE TITLE
[Venue] Dallas: Floor Plan - PDF not loading

### ISSUE THREAD

**Issue by CamLow** [MicroTekAppDev/Attune.Website.Issues#38]
**Page Info**
Page URL: https://test-umb.attune.com/spaces/united-states/texas/dallas/attune-dallas/
Section: Floor Plan

**Describe the bug**
When I hit the green button to view the Handbook i get a black blank screen

**Additional context**
Testing in Chrome on my laptop

**Comment by aj-mclabs** [comment]
Copy fixed. Cannot replicate black screen for PDF error.

**Comment by bdsoko** [comment]
@aj-mclabs - could not reproduce on a chrome book.  Earlier today, I’ve tested on all major web browsers without reproducing as well.

**Comment by aj-mclabs** [comment]
Spoke with @CamLow. Seems to be working for her now ¯\_(ツ)_/¯
