### ISSUE TITLE
[Visitor] Map Display

### ISSUE THREAD

**Issue by kopiola** [MicroTekAppDev/Attune.Website.Issues#39]
**Page URL**
Page URL: 

https://test-umb.attune.com/spaces/united-states/kentucky/louisville/louisville-center/visitor-info/
--

**Describe the bug**
Using IE 11.  This happened on both venue pages that I have looked at so far (Louisville and Baltimore).  Using the direct navigate buttons to view Hotel or FAQ info and then going to Map, the top portion/address is cut off.

**To Reproduce**
1. Go to https://test-umb.attune.com/spaces/united-states/kentucky/louisville/louisville-center/visitor-info/
2. Click on 'Hotel' button in the middle of the page.
3. Click on 'Map' Button.

**Expected behavior**
I would expect to see the full address, but it's cut off by the page header.

**Screenshots**
![image](https://user-images.githubusercontent.com/55112627/64570101-1a4cc400-d325-11e9-8591-388563f639f7.png)

**Desktop (please complete the following information):**
 - Browser: IE 11

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aj-mclabs** [comment]
This is functioning as intended. Anytime the user scrolls up on the page (or clicks a shortcut that scrolls them up the page), the navigation comes back into the viewport (in this case covering the address). We'll connect with the dev team to see if there's anything that can be done about this.

**Comment by aj-mclabs** [comment]
Unfortunate side-effect of our hide-away navigation. Cannot be changed without negatively affecting nav functionality.
