### ISSUE TITLE
[Venue] Network Locations: Breadcrumb - All links go back to search page

### ISSUE THREAD

**Issue by angels-mclabs** [MicroTekAppDev/Attune.Website.Issues#41]
**Page URL**
Page URL: https://test-umb.attune.com/spaces/australia/victoria/melbourne/melbourne-center/

**Describe the bug**
Navigating using the breadcrumb at the bottom of the page is confusing, if I click Australia to maybe see what else you have in Australia I get sent to the location search again. 

![Melbourne Breadcrumb](https://user-images.githubusercontent.com/55002064/64619711-24fc6d00-d3a8-11e9-8e95-c55f6da8cfb2.png)

**Comment by aj-mclabs** [comment]
Removing breadcrumb from all Venue and Visitor pages

**Comment by aj-mclabs** [comment]
Breadcrumb has been removed from all venue and visitor pages
