### ISSUE TITLE
[Resources] Infographic: Choosing Virtual Training Provider - No content on page

### ISSUE THREAD

**Issue by Jason-Howe** [MicroTekAppDev/Attune.Website.Issues#45]
https://test-umb.attune.com/insights/resources/infographics/choosing-a-virtual-training-provider/

**Describe the bug**
the link to choosing a virtual training provider goes to blank page.

**To Reproduce**
1. Go to https://test-umb.attune.com/insights/resources/
2. Click on Choosing A virtual training provider
3. Blank page appears

**Expected behavior**
I expected a page to load that explained to me how to choose a virtual training provider.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser Chrome
 - Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by aj-mclabs** [comment]
Republished image component. Should be fixed. Please re-test!

**Comment by Jason-Howe** [comment]
Resolved!
