### ISSUE TITLE
[Visitor] Hotels - Phone numbers clipping through box

### ISSUE THREAD

**Issue by CamLow** [MicroTekAppDev/Attune.Website.Issues#46]
**Is your feature request related to a problem? Please describe.**
The telephone number for the all of the Hotels is outside of the line and looks unprofessional.
This is viewed for Dallas, New York, WDC and Dulles, and likely the other MicroTek facilities.https://test-umb.attune.com/spaces/united-states/new-york/new-york/attune-new-york-city/visitor-info/

**Describe the solution you'd like**
Move the print to the left.

**Describe alternatives you've considered**

**Additional context**

**Comment by bdsoko** [comment]
@CamLow - Can't reproduce.  What OS, web browser and resolution did you use?

**Comment by tomwidel** [comment]
@CamLow - I have updated the column sizing for smaller screen resolutions. Can you please re-test and let us know if the issue is fixed?

**Comment by CamLow** [comment]
The issue appears fixed.



Camille Lowe
MicroTek - www.mclabs.com<blocked::http://www.mclabs.com/>
V: 630.719.0212
E: camillel@mclabs.com<mailto:camillel@mclabs.com>
