### ISSUE TITLE
[Venue] DC: Floor Plan - Showing multiple floor plans

### ISSUE THREAD

**Issue by bdsoko** [MicroTekAppDev/Attune.Website.Issues#47]
**Page Info**
Page URL: https://test-umb.attune.com/spaces/united-states/district-of-columbia/washington/attune-washington-d-c/

Section: floor plans

**Describe the bug**
Noticed floor plan was rotating which caught my eye.  Do we have multiple floors at this location?

**Screenshots**

**Additional context**

**Comment by aj-mclabs** [comment]
Fixed.
