### ISSUE TITLE
[Venue-Dallas] Virtual - Link to shows MicroTek PDF

### ISSUE THREAD

**Issue by angels-mclabs** [MicroTekAppDev/Attune.Website.Issues#48]
**Page Info**
Page URL: https://test-umb.attune.com/spaces/united-states/texas/dallas/attune-dallas/
Section: Choosing to look at the "Virtual Solutions Guide" opens over the active tab. I had expected it to open/download into a new tab.

**Comment by connorsli** [comment]
This will now open the PDF in a new tab. Will replace placeholder as son as the booklet is finalized.

**Comment by angels-mclabs** [comment]
Retested that this does now open in a new window.
