### ISSUE TITLE
[Venue] Sub Nav Links - Suggest Change

### ISSUE THREAD

**Issue by angels-mclabs** [MicroTekAppDev/Attune.Website.Issues#49]
In the venue for example: https://test-umb.attune.com/spaces/united-states/texas/dallas/attune-dallas/

the jump nav includes features/amenities/catering/floor plan/hotels/visitor Info, FAQ

It does not have variable layouts which can probably replace hotels? Hotel and Visitor Info go together.

**Comment by aj-mclabs** [comment]
Sure! So just to confirm...

For our venues it would be:

 Features | Amenities | Catering | Layouts | Floor Plan | Visitor Info | FAQ

**What would we want it to look like at network venues where we don't have the Layout or Floor Plan components?**

Currently it is:
 Features | Amenities | Catering | Virtual Attendance | Hotels | Visitor Info | FAQ

Example:
https://www.attune.com/spaces/united-states/illinois/oak-brook/oak-brook-center/

**Comment by angels-mclabs** [comment]
I think it would be ok to make it shorter, remove Hotels because it is on the visitor info.

**Comment by aj-mclabs** [comment]
Attune locations now have a standardized quick nav. Network locations have been standardized and remain unchanged per group feedback.
