### ISSUE TITLE
[Global] Main Nav - Large title bar on phone/tablet

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#5]
**Page Info**
All

**Describe the bug**
The Title bar when using a phone / tablet appears to be take up way to much screen real estate.   The hamburger icon seems huge.    Making it smaller would show more information to the users.

**Screenshots**
Screenshots attached as files.
![Phone](https://user-images.githubusercontent.com/55096138/64538702-b5707a00-d2e2-11e9-9036-0d32c030ddd0.png)
![Tablet](https://user-images.githubusercontent.com/55096138/64538706-b5707a00-d2e2-11e9-8624-6549eb16d883.jpg)

 

**Additional context**

**Comment by tomwidel** [comment]
Per @aj-mclabs , updated user experience to work just like desktop mode.
