### ISSUE TITLE
[Pillar] Spaces to Meet: Banner - Rotation arrows hard to see

### ISSUE THREAD

**Issue by angels-mclabs** [MicroTekAppDev/Attune.Website.Issues#50]
**Page Info**
Page URL: https://test-umb.attune.com/
Section: On the main page when it scrolls to "spaces to meet" there is no arrow to scroll to the next picture unless you hover over and it becomes highlighted green.

**Comment by aj-mclabs** [comment]
@bdsoko any way we can implement an option to have darker arrows?

**Comment by bdsoko** [comment]
Back/Forth arrow color has been change to charcoal.

@aj-mclabs - Issue might popup again if/when background images are changed to something darker.
