### ISSUE TITLE
[Search] Choosing one of the "other" venues seems to reload the search

### ISSUE THREAD

**Issue by angels-mclabs** [MicroTekAppDev/Attune.Website.Issues#51]
**Page URL**
Page URL: https://test-umb.attune.com/spaces/united-states/california/glendale/meeting-and-training-rooms/

**Describe the bug**
My results for an Ontario, CA search returned Los Angeles along with a listing of other cities with venues. When I click the links for "Long Beach, California" the search reloads with that location and returns the same result. I see that it says to click here to request more information above, however, I think it would make sense to have something where I click that link and it takes me to a contact page that explains Attune's network of facilities and that we'd be happy to provide details about this network location.

**Comment by angels-mclabs** [comment]
I see that the page appears to do a new search near the selected facility. I like that functionality, it just wasn't clear what was happening. This is probably a non-issue if we just add click to search near these locations.

**Comment by bdsoko** [comment]
@angels-mclabs  - We've made several changes that improve the overall user experience when searching for venues - new layout, animations, etc...  I hope these changes address your issue.

@aj-mclabs  - re: the link to click here, seems out off place.  Can we do something about this?

**Comment by aj-mclabs** [comment]
Closing this ticket, as initial issue has been resolved. Opened separate feature request ticket for suggestion mentioned above: #166 . To follow the issue, please reply to that thread.
