### ISSUE TITLE
[Venue] Venue Photos - Not fluid scrolling and images too large on IE11

### ISSUE THREAD

**Issue by kopiola** [MicroTekAppDev/Attune.Website.Issues#52]
**Page Info**
Page URL: https://test-umb.attune.com/spaces/united-states/maryland/baltimore/baltimore-center/
Section: Top

**Describe the bug**
When navigating down the page, the facility pictures are the 1st thing you come to and they take up more than the full screen (IE11).  Also, the scrolling between the 4 pictures is not fluid.  It's difficult to determine the reason as to why the scrolling starts and stops because it doesn't always scroll through the pictures, which may have to due with the picture being larger than the full screen.

**Screenshots**

**Additional context**

**Comment by kopiola** [comment]
I noticed the same thing on the next page I viewed for Columbia, MD.  I opened the pages in both Chrome and IE11.  The pictures rendered and scrolled fine in Chrome.  So, this may just be due to the browser, IE11.

**Comment by connorsli** [comment]
@kopiola Pictures not scrolling can be caused by your mouse position. If you are on top of the picture banner the timer stops but once your mouse goes above/below the picture the timed scroll will resume.
