### ISSUE TITLE
[Visitor] Hotels - Text clipping through box (Duplicate of #46)

### ISSUE THREAD

**Issue by kopiola** [MicroTekAppDev/Attune.Website.Issues#53]
**Page Info**
Page URL: https://test-umb.attune.com/spaces/united-states/maryland/baltimore/baltimore-center/visitor-info/
Section: Hotels

**Describe the bug**
There is text outside the box on the right side "Attune Rate".  Screenshot below.

**Screenshots**
![image](https://user-images.githubusercontent.com/55112627/64716045-3ec0b180-d487-11e9-851d-3957bdd8ad93.png)

**Additional context**

**Comment by kopiola** [comment]
this is on the Columbia, MD page as well.  It's the same hotel info.

https://test-umb.attune.com/spaces/united-states/maryland/columbia/columbia-center/visitor-info/
--

**Comment by aj-mclabs** [comment]
Cannot replicate in Chrome

@kopiola what browser are you using when seeing this?

Reassigned to @bdsoko as a bug

**Comment by aj-mclabs** [comment]
Thread locked. This is a duplicate of #46. Please move all discussion on this topic to that thread

**Comment by bdsoko** [comment]
Closing this issue as we are using issue #46 to track comments.
