### ISSUE TITLE
[Visitor] Bad reviews on map pins

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#58]
**Page Info**
https://test-umb.attune.com/spaces/united-states/illinois/lombard/lombard-center/visitor-info/

**Describe the bug**
We should consider hiding reviews from the Google Maps pin.   I found one pin with a 1 star review.   Looks bad.

**Screenshots**
![2019-09-11_13-47-07](https://user-images.githubusercontent.com/55096138/64725872-16db4900-d49b-11e9-9990-39f4e802685b.jpg)

**Comment by aj-mclabs** [comment]
Embedded Google Map has been changed to use venue location pin with better review score.
