### ISSUE TITLE
[Visitor] Hotel: Embassy Suites - Phoenix Downtown North - Link Broken

### ISSUE THREAD

**Issue by kimm-att** [MicroTekAppDev/Attune.Website.Issues#59]
https://test-umb.attune.com/spaces/united-states/arizona/phoenix/phoenix-center/visitor-info/

**Describe the bug**
Hotel link for Embassy Suites - Phoenix Downtown North returns an error when you click View Rates

**Comment by connorsli** [comment]
Link has been fixed and is resolving with our prefilled group code
