### ISSUE TITLE
"Search our Network" button cut off on Phone

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#6]
**Page Info**
Home Page  http://test-umb.attune.com

**Describe the bug**
"Search our Network" button cut off on Phone

**Screenshots**
![Screenshot_20190908-181144](https://user-images.githubusercontent.com/55096138/64538913-1e57f200-d2e3-11e9-9c55-fe4b7500abd6.png)

**Additional context**

**Comment by bdsoko** [comment]
Issue should be resolved.  Please verify.
