### ISSUE TITLE
[Visitor - Tampa] Hotels - Reservation link has expired

### ISSUE THREAD

**Issue by kimm-att** [MicroTekAppDev/Attune.Website.Issues#60]
https://test-umb.attune.com/spaces/united-states/florida/tampa/tampa-center/visitor-info/

Hotel link opens a general search page for Tampa instead of the actual hotel details page

**Comment by aj-mclabs** [comment]
Cannot replicate. Is this still an issue on your end @kimm-att ?

**Comment by kimm-att** [comment]
Yes. The page it opens yields all Tampa hotels in the IHG brands. It should open the hotel with which we have a contract, the Crowne Plaza Tampa Westshore at 5303 W Kennedy Blvd
Tampa, FL 33609. I can't find it on the page. When i key in the address, it's called the Alba Hotel. This might be a hotel issue, but needs to get fixed one way or the other.

**Comment by connorsli** [comment]
I was able to reproduce this. I tried the button and went directly to the hotel spreadsheet and it showed the same thing. My guess is it's a redirect on their side. Will probably need to get an updated link.

**Comment by aj-mclabs** [comment]
Reached out to Beth to see about getting a new reservation link.

**Comment by Beth-B** [comment]
Our current MicroTek website does not have a listing for Tampa- not sure why there is one showing on the new website-  unless it was a requested add, but I am not aware of it.

Our previous partner was Tech Sherpas at a different address- that listing was removed and the hotel contract expired and was not renewed.  This would be why the link is no longer working. 

We do not have any current hotel contracts in Tampa, or for New Horizons Tampa.  If we are adding them to the website, and need to add a hotel, we can include them in our 2020 RFP- but we do not currently have any contracted hotel relationships in Tampa.

**Comment by kimm-att** [comment]
This is our current Tampa partner as Tech Sherpas closed. The hotel is a suggestion, which is a reference to another case about hotel language where we don't have a hotel contract but use this hotel as a suggestion. The hotel on this page has been changed to the Alba Hotel, so it no longer exists as an IHG property.

**Comment by aj-mclabs** [comment]
Changed this hotel to a non-partner listing. Also changed hotel name to Alba Hotel and updated Google Maps link. Please re-check @kimm-att

**Comment by kimm-att** [comment]
Although the hotel listing looks OK, couple of things still wrong. 
1) the "Hotels" shortcut is missing the the navigation bar on the Tampa Center page. 
2) Hotel Alba (formerly an IHG brand) was our old hotel partner for Tech Sherpas. It is nowhere near the New Horizons. We should post a new hotel. There is a Hilton Garden Inn a couple of blocks away.

**Comment by aj-mclabs** [comment]
Was told to remove hotels from quick nav on network locations per Angel. See thread here: #49 
Let me know if there needs to be a larger discussion on this topic ASAP, as we're about to go through all venue pages to standardize nav and buttons.

@connorsli can you address the number 2 bullet above? Thanks.

**Comment by kimm-att** [comment]
Larger discussion!!
Her objections are probably similar to my case re: hotel partners that aren’t partners and the “Attune Rate”. Let’s not make overarching changes without talking. If we decide it’s the way to go, then OK.

**Comment by connorsli** [comment]
The "Hilton Garden Inn Tampa Airport" has been added as a non-partner hotel.
