### ISSUE TITLE
Inconsistent Headers

### ISSUE THREAD

**Issue by kimm-att** [MicroTekAppDev/Attune.Website.Issues#62]
https://test-umb.attune.com/spaces/united-states/california/redwood-city/redwood-city-center/visitor-info/
AND
https://test-umb.attune.com/spaces/united-states/california/los-angeles/los-angeles-center/visitor-info/

Headers do not read MAP, HOTELS, and VISITOR FAQ

Redwood City says Directions&Parking | HOTELS | Visitor FAQ
Los Angeles says MAP | Hotel Listings | Visitor FAQ

**Comment by connorsli** [comment]
All 3 pages above have had navigation fixed.
