### ISSUE TITLE
Washington DC Visitor - Back button too small for text

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#64]
**Page Info**
https://www.attune.com/spaces/united-states/district-of-columbia/washington/attune-washington-d-c/visitor-info/
**Describe the bug**
![2019-09-12_10-17-24](https://user-images.githubusercontent.com/55096138/64797207-a38f1100-d546-11e9-84de-b2790632084f.jpg)

**Comment by aj-mclabs** [comment]
Changed copy to Attune D.C.
