### ISSUE TITLE
[Visitor] Back button - Inconsistent functionality

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#65]
**Page Info**
https://test-umb.attune.com/spaces/united-states/massachusetts/burlington/attune-boston/visitor-info/
https://test-umb.attune.com/spaces/switzerland/zurich/zurich/zurich-center/

**Describe the bug**
All of the non attune pages have a back icon within the button,  the attune locations do not.
Standardize icon and text?

**Screenshots**
![2019-09-12_10-22-54](https://user-images.githubusercontent.com/55096138/64797810-9d4d6480-d547-11e9-9a98-4c49992c6a7c.jpg)
![2019-09-12_10-23-11](https://user-images.githubusercontent.com/55096138/64797811-9d4d6480-d547-11e9-9ed8-33334f3de842.jpg)

**Comment by aj-mclabs** [comment]
In the process of switching all to emulate Attune locations.

**Comment by aj-mclabs** [comment]
Also, as an FYI, that icon indicated the link will open in a new tab

**Comment by aj-mclabs** [comment]
All buttons have now been standardized to say 'Back to Venue'
