### ISSUE TITLE
Free Tool Kit Pic / Link doesn't open new windows

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#66]
**Page Info**
https://test-umb.attune.com/insights/blog/posts/2015/november/7-ways-to-eliminate-distractions-during-virtual-learning/

**Describe the bug**
The Free Tool Kit Picture / Link doesn't open a new page/tab instead it changes the current window.   I believe it is supposed to open a new page/tab

**Screenshots**
![2019-09-12_10-23-11](https://user-images.githubusercontent.com/55096138/64798487-b571b380-d548-11e9-8651-3e97b9d4717d.jpg)

**Additional context**

**Comment by connorsli** [comment]
Fixed. The CTA now opens in a new tab.
