### ISSUE TITLE
Number List looks strange on this blog.  Size isn't Right.

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#67]
**Page Info**
https://test-umb.attune.com/insights/blog/posts/2015/august/video-conferencing-etiquette-101/

**Describe the bug**
Number List looks strange on this blog.  Size isn't Right.

**Screenshots**
![2019-09-12_10-34-34](https://user-images.githubusercontent.com/55096138/64798621-f2d64100-d548-11e9-991d-01f60b438529.jpg)

**Comment by connorsli** [comment]
Removed inline numbered list and replaced with normal text.  May want the indents or not. I'll leave that up to @aj-mclabs

**Comment by esuger** [comment]
It's better.   You can close if you want to.
