### ISSUE TITLE
Sub Bulleted Items have wrong Font Size

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#68]
**Page Info**
https://test-umb.attune.com/insights/blog/posts/2017/may/how-to-develop-your-complete-training-budget/

**Describe the bug**
The sub bullet-ed items have a font that is too large.  It looks strange having the same size as the overall header.

**Screenshots**
![2019-09-12_10-44-22](https://user-images.githubusercontent.com/55096138/64799525-80fef700-d54a-11e9-8520-782066cedba7.jpg)

**Comment by connorsli** [comment]
Both of these blogs have been formatted.
