### ISSUE TITLE
[Book Now] Form - Validation does not allow valid phone #

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#69]
**Page URL**
https://www.attune.com/book-now/

Book Now Form will not allow valid phone #

**To Reproduce**
Go to book now site and try phone number 111-111-1111 and then switch it to a valid one.

**Expected behavior**
Should have allowed a valid phone number

**Screenshots**
![2019-09-12_10-54-43](https://user-images.githubusercontent.com/55096138/64800311-fd460a00-d54b-11e9-84e0-6a513eeaa76a.jpg)

**Desktop (please complete the following information):**
Windows 10 , Chrome

**Comment by connorsli** [comment]
@tomwidel Eric had an existing thread with a screenshot.

**Comment by bdsoko** [comment]
@esuger - We removed the phone number validation as it should not have been enabled.  Doing so allows us to support international numbers.  Please retest.

**Comment by esuger** [comment]
I'm not able to get past the telephone number requirement.  Thanks.
