### ISSUE TITLE
[Insights] Layout - "View Resources" button too low

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#7]
**Page Info**
http://test-umb.attune.com/insights

**Describe the bug**
Compared to the reset of the site the "View Resources" button is too low on the insights screen when viewed from a tablet.

**Screenshots**
![Screenshot_20190907-214553](https://user-images.githubusercontent.com/55096138/64539250-c968ab80-d2e3-11e9-9de4-d55ecd336391.jpg)

**Additional context**

**Comment by aj-mclabs** [comment]
Increased component padding. Please recheck.
