### ISSUE TITLE
[Venue] Hotels - Make button open straight to hotel section on visitor page

### ISSUE THREAD

**Issue by marax-mclabs** [MicroTekAppDev/Attune.Website.Issues#71]
**Page Info**
Page URL: https://test-umb.attune.com/spaces/united-states/district-of-columbia/washington/attune-washington-d-c/
Section: Nearby Partner Hotels

When you click on "View Hotels" the first thing you see is Visitor Information, ie, address, parking, etc...  You need to scroll to the bottom to find Hotel information.  I was not expecting to see the address and parking here.  Maybe this should be mentioned in the section leading to this page?

**Comment by aj-mclabs** [comment]
Suggestion accepted. Fix being implemented.

**Comment by aj-mclabs** [comment]
All 'View Hotels' buttons now open directly to the Hotels section on the visitor page
