### ISSUE TITLE
Hour of Operation

### ISSUE THREAD

**Issue by marax-mclabs** [MicroTekAppDev/Attune.Website.Issues#72]
**Page Info**
Page URL: https://test-umb.attune.com/spaces/united-states/illinois/chicago/attune-chicago/
Section: Frequently Asked Questions

Under the Venue's Hours of Operation, I recommend adding "Monday through Friday" next to 8am-6pm.

**Comment by connorsli** [comment]
The answer has been updated to read 

"Standard hours are 8am - 6pm, Monday through Friday. If you require access outside of standard hours, please ask your Attune account manager for more information."

**Comment by aj-mclabs** [comment]
This has been added to all Attune venue pages.
