### ISSUE TITLE
[Venue - Attune] Add IACC Certification component to applicable venues

### ISSUE THREAD

**Issue by marax-mclabs** [MicroTekAppDev/Attune.Website.Issues#73]
**Page Info**
Page URL:  

Already spoke to AJ about this, but I recommend we display the IACC certification for the MicroTek sites where it applies.

**Comment by aj-mclabs** [comment]
Suggestion being implemented.

IACC certified venues will get a dedicated IACC component talking about the certification.

**Comment by aj-mclabs** [comment]
A dedicated IACC component has been added to each certified location
