### ISSUE TITLE
[Venue - Phoenix] Text edits - Asterisks to add a in front of variety and to in front of execute. 

### ISSUE THREAD

**Issue by angels-mclabs** [MicroTekAppDev/Attune.Website.Issues#74]
**Page Info**
Page URL: https://test-umb.attune.com/spaces/united-states/arizona/phoenix/training-rooms/
Section: copy and paste section title here

It can be challenging to locate a training room that meets all the needs of your company. Having the environment and atmosphere is critical to making your professional development event a success. Amenities at our locations include complimentary snacks, catered meals, high-speed internet connection, and hotel and transportation assistance to and from venues. Additionally, our training rooms offer virtual training infrastructure, cloud-based labs, advanced collaboration tools, and classrooms equipped with state-of-the-art computers. Training can come in several shapes and forms, and our rooms can be adapted to any practice a client may request.
Situated within Phoenix city limits, our training rooms offer the flexibility to utilize a wide range of training types and provide **a variety** of unique ways to engage with students. Specifically built to aid companies **to execute** hands-on and virtual training exercises, these rooms offer options for both in-person and remote training capabilities. Our training spaces boast on-site technical staff to deal with any IT troubleshooting clients may need. Furthermore, our resident hospitality staff has been professionally trained to anticipate the needs of our attendees. They are open to any queries you may have while on-site.
Attune believes that training is necessary for a company's future success. To this end, we provide training rooms that users can gear to all types of exercises. We have rooms dedicated for presentations and others that offer a more formal, corporate atmosphere. We also provide locations of various sizes that can accommodate parties of every size, from the close-knit to a lecture-hall type of layout. Contact Attune today to book your training room now!
**Describe the bug**

**Screenshots**

**Additional context**

**Comment by connorsli** [comment]
@angels-mclabs I'm not sure where this block of text lives. Could you give a section title or screenshot of the affected area?

**Comment by aj-mclabs** [comment]
Clarification required. Not understanding what the requested fix is.

**Comment by angels-mclabs** [comment]
Navigate to https://test-umb.attune.com/spaces/united-states/arizona/phoenix/training-rooms/, then scroll to the area with "Training in Phoenix, AZ". It also listed complimentary snacks, the word complimentary needs to be 
![Phoenix](https://user-images.githubusercontent.com/55002064/64976055-0994d480-d876-11e9-888c-5de76ef771ba.png)
removed.

**Comment by connorsli** [comment]
These changes have been made and should be reflected across training keyword pages.

**Comment by angels-mclabs** [comment]
Changes look good. Thanks.
