### ISSUE TITLE
[Venue - Attune] Floor Plan - Images do not expand when clicked

### ISSUE THREAD

**Issue by angels-mclabs** [MicroTekAppDev/Attune.Website.Issues#78]
**Page Info**
Page URL: 

https://test-umb.attune.com/spaces/united-states/district-of-columbia/washington/attune-washington-d-c/
--
The floor plan for Dallas, for example, can be enlarged by clicking on the image. Because the images are small it would be good to have the others with this capability.

**Comment by connorsli** [comment]
This functionality (lightbox) has been changed to mirror the Dallas page.
