### ISSUE TITLE
[Visitor - Houston] Hotel - La Quinta link not working

### ISSUE THREAD

**Issue by kimm-att** [MicroTekAppDev/Attune.Website.Issues#79]
https://test-umb.attune.com/spaces/united-states/texas/houston/houston-center/visitor-info/

La Quinta hotel link returns the Townplace Suites website.

Also, the headers are inconsistent.
Houston shows MAP | Hotel Listings | Visitor FAQ

**Comment by connorsli** [comment]
Link has been fixed and now resolves correctly. The "Hotel Listings" nav as been changed to "Hotels"
