### ISSUE TITLE
[Homepage] Banners - Text on images difficult to read

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#8]
**Page Info**
http://test-umb.attune.com

**Describe the bug**
On a phone / tablet the text on the rotating images overlays the image more.  The dark text when it's over a dark image  (people's hair) it becomes difficult to read.

**Screenshots**
![Screenshot_20190909-092257](https://user-images.githubusercontent.com/55096138/64539390-05037580-d2e4-11e9-8b68-f016249a18a9.png)

**Additional context**

**Comment by aj-mclabs** [comment]
The following header banners now have dedicated mobile versions that will replace standard variants at smaller screen resultions:
https://test-umb.attune.com/
https://test-umb.attune.com/spaces-to-meet/
https://test-umb.attune.com/spaces-to-train/

Please recheck.

**Comment by esuger** [comment]
Looks good.  We probably have to the same thing to the rest of the pictures on this page so the words don't wash out.

**Comment by aj-mclabs** [comment]
Fixed. Please confirm!

**Comment by esuger** [comment]
Looks good.
