### ISSUE TITLE
[Visitor Info] Quick Nav - Headings incorrect, hotels missing

### ISSUE THREAD

**Issue by kimm-att** [MicroTekAppDev/Attune.Website.Issues#80]
https://test-umb.attune.com/spaces/united-states/washington/seattle/seattle-center/visitor-info/

https://test-umb.attune.com/spaces/united-states/wisconsin/madison/madison-center/visitor-info/

https://test-umb.attune.com/spaces/united-states/wisconsin/milwaukee/milwaukee-center/visitor-info/

All Page headers read MAP | Hotel Listings | Visitor FAQ instead of just "Hotels"
Madison and Milwaukee both have a hotel slice with content, but no hotels listed.

**Comment by connorsli** [comment]
I have unpublished the empty hotel slices.

**Comment by aj-mclabs** [comment]
@connorsli need to add new list of domestic hotels supplied by Mara's team (list given to Marketing 9/12). All venues should now have at least one hotel.}
@kimm-att will notify you when these are ready for recheck.

**Comment by aj-mclabs** [comment]
@connorsli still no hotels on Madison?
https://test-umb.attune.com/spaces/united-states/wisconsin/madison/madison-center/visitor-info/

**Comment by connorsli** [comment]
@aj-mclabs I believe this is good to close. I checked all stick Nav text and Madison has hotels now.

**Comment by kimm-att** [comment]
the last Madison hotel has no contact info

**Comment by connorsli** [comment]
That hotel has had its contact info published.
