### ISSUE TITLE
(?) [GLOBAL] Internal links do not open in new tab

### ISSUE THREAD

**Issue by kimm-att** [MicroTekAppDev/Attune.Website.Issues#81]
Note sure if this is a problem or is just a fact of life, but when I hit an internal link on the iPad, it never opens a new tab. It always just changes the current tab. (External links open a new tab.)

iPad
Safari Browser

**Comment by aj-mclabs** [comment]
Browser should be irrelevant. In most cases, this is a manual option chosen individually for every link on the site. We would need reports of specific instances where opening in the same tab would not make sense.

**Comment by kimm-att** [comment]
all internal links open in same tab. external links in new tab. ALL
