### ISSUE TITLE
[Keyword Override] City Keyword - Incorrect city content being pulled in

### ISSUE THREAD

**Issue by Jason-Howe** [MicroTekAppDev/Attune.Website.Issues#82]
**Page Info**
https://test-umb.attune.com/spaces/united-states/california/san-francisco/classrooms

**Describe the bug**
Details about facility are for Atlanta not San Francisco

**Comment by Jason-Howe** [comment]
https://test-umb.attune.com/spaces/united-states/california/san-francisco/computer-rooms

https://test-umb.attune.com/spaces/united-states/california/san-francisco/conference-rooms

Same Issue on these two as well.

**Comment by Jason-Howe** [comment]
https://test-umb.attune.com/spaces/united-states/district-of-columbia/washington/classrooms
https://test-umb.attune.com/spaces/united-states/district-of-columbia/washington/conference-rooms
https://test-umb.attune.com/spaces/united-states/district-of-columbia/washington/computer-rooms

Facility details are Atlanta not DC.

**Comment by aj-mclabs** [comment]
Investigating.

**Comment by aj-mclabs** [comment]
Fixed.
