### ISSUE TITLE
[Blog] 2017: Interlinking - Link returns to same page

### ISSUE THREAD

**Issue by Jason-Howe** [MicroTekAppDev/Attune.Website.Issues#83]
**Page Info**
https://test-umb.attune.com/insights/blog/posts/2017/june/training-program-planning-worksheet/

**Describe the bug**
clicked on  "Download Your Worksheet" and expected a document but was returned back to the same page I started on above.

**Comment by aj-mclabs** [comment]
Created a dedicated MQL landing page for this piece of content. The link in question now links to that page.
