### ISSUE TITLE
[Venue - Winnepeg] Directions - Facility name missing

### ISSUE THREAD

**Issue by kimm-att** [MicroTekAppDev/Attune.Website.Issues#86]
https://test-umb.attune.com/spaces/canada/manitoba/winnipeg/winnipeg-center/visitor-info/

The copy does not mention the name of the facility partner as the others do.

**Comment by aj-mclabs** [comment]
This venue is not named on our current site. 
Investigating.

**Comment by connorsli** [comment]
Added Global Knowledge name which matched the provided RMS ID.
