### ISSUE TITLE
(?) [MISC] Warner Robins, Georgia NC

### ISSUE THREAD

**Issue by CamLow** [MicroTekAppDev/Attune.Website.Issues#88]
https://test-umb.attune.com/spaces/united-states/georgia/warner-robins/computer-rooms/here
and
https://test-umb.attune.com/spaces/united-states/stockbridge/computer-rooms/
**Describe the bug**
In the section "Computer Rooms in Warner Robins Georgia"  the city is referenced as Warner Robins, Georgia NC.  The same verbiage is referenced in "Computer Rooms in Stockbridge Georgia. 

See text below
Computer Rooms in Warner Robins, Georgia

A space that offers the use of computers for corporate clients is a necessity in a modern enterprise. Finding the right computer room is a crucial step in ensuring that conference attendees have access to the infrastructure they need to participate in training or presentations. Attune has perfected the art of corporate computer room rental, and our facility in Warner Robins, Georgia, NC offers all the infrastructure and utilities a company may need.

**Comment by aj-mclabs** [comment]
@CamLow neither of these pages should exist. Are you getting pages for these? According to the system, they don't exist.

**Comment by CamLow** [comment]
Yes I am.



Camille Lowe
MicroTek - www.mclabs.com<blocked::http://www.mclabs.com/>
V: 630.719.0212
E: camillel@mclabs.com<mailto:camillel@mclabs.com>

**Comment by angels-mclabs** [comment]
If you go to https://test-umb.attune.com/spaces/united-states/georgia/atlanta/computer-rooms/, one of the test links, then click on Warner Robbins, Georgia under additional Venues, you will arrive at https://test-umb.attune.com/spaces/united-states/georgia/warner-robins/computer-rooms/ 

Next scroll down and you will see "Computer Rooms in Waner Robins, Georgia. This text needs editing.

**Comment by angels-mclabs** [comment]
Left some text changes on this attachment.
![Warner Robins](https://user-images.githubusercontent.com/55002064/64991857-496cb380-d898-11e9-9623-4193036f73e5.png)

**Comment by connorsli** [comment]
Fixed. @aj-mclabs

**Comment by CamLow** [comment]
Confirmed.

Thanks!



Camille Lowe
MicroTek - www.mclabs.com<blocked::http://www.mclabs.com/>
V: 630.719.0212
E: camillel@mclabs.com<mailto:camillel@mclabs.com>
