### ISSUE TITLE
[Resources] Video: Tracker: No content on page

### ISSUE THREAD

**Issue by esuger** [MicroTekAppDev/Attune.Website.Issues#95]
**Page Info**
https://test-umb.attune.com/insights/blog/posts/2018/september/4-tips-to-meet-your-employee-training-objectives-and-improve-roi/

**Describe the bug**
Link "RELATED VIDEO: Tracker - The Ultimate Event Management Portal" on page opens a blank page.

**Comment by esuger** [comment]
On this page too:  https://test-umb.attune.com/insights/blog/posts/2018/september/three-planning-keys-to-creating-a-seamless-corporate-training-program/

**Comment by aj-mclabs** [comment]
Fixed.
