### ISSUE TITLE
[Visitor - Melbourne] Directions - Grammar

### ISSUE THREAD

**Issue by kimm-att** [MicroTekAppDev/Attune.Website.Issues#99]
https://test-umb.attune.com/spaces/australia/victoria/melbourne/melbourne-center/visitor-info/

Where the facility name is described. Verbiage is:
The facility name you are looking for is Cliftons, an Attune partner facility.

Please change to 
The facility name is Cliftons, an Attune partner facility.

**Comment by aj-mclabs** [comment]
Fixed.
